/* Editorial operating system: Activity is a quiet learning ledger where evidence, ownership, outcome, and the next return path stay connected. */
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarPlus, Check } from "lucide-react";
import { Link } from "wouter";
import { SectionLabel, SignalTag } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";
import { getWorkflowRecords, removeWorkflowRecord, type WorkflowRecord } from "../lib/workflowRecords";
import { ProductShell } from "./ProductFlows";

type ActivityFilter = "all" | "decision" | "event" | "application";

export function ActivityWorkspace() {
  const { t, formatNum, isRTL } = useLocale();
  const [records, setRecords] = useState(() => getWorkflowRecords());
  const [filter, setFilter] = useState<ActivityFilter>("all");
  const [followUps, setFollowUps] = useState<Record<string, boolean>>(() => {
    if (typeof window === "undefined") return {};
    try { return JSON.parse(window.localStorage.getItem("asaasi-event-follow-ups") ?? "{}"); } catch { return {}; }
  });
  const [reviewed, setReviewed] = useState<Record<string, boolean>>(() => {
    if (typeof window === "undefined") return {};
    try { return JSON.parse(window.localStorage.getItem("asaasi-workflow-reviewed") ?? "{}"); } catch { return {}; }
  });
  useEffect(() => { window.localStorage.setItem("asaasi-event-follow-ups", JSON.stringify(followUps)); }, [followUps]);
  useEffect(() => { window.localStorage.setItem("asaasi-workflow-reviewed", JSON.stringify(reviewed)); }, [reviewed]);

  const decisions = records.filter((record) => record.kind === "decision");
  const learnedDecisions = decisions.filter((record) => Boolean(record.outcome));
  const openDecisions = decisions.filter((record) => !record.outcome);
  const shown = filter === "all" ? records : records.filter((record) => record.kind === filter);
  const clear = (id: string) => { removeWorkflowRecord(id); setRecords(getWorkflowRecords()); setReviewed((current) => { const { [id]: _, ...rest } = current; return rest; }); };
  const outcomeLabel = (record: WorkflowRecord) => record.outcome === "keep" ? t("Keep direction", "أبقِ الاتجاه") : record.outcome === "change" ? t("Change approach", "غيّر النهج") : record.outcome === "stop" ? t("Stop bet", "أوقف الرهان") : t("Awaiting review", "بانتظار المراجعة");
  const labels: Record<ActivityFilter, string> = { all: t("All activity", "كل النشاط"), decision: t("Decisions", "القرارات"), event: t("Events", "الفعاليات"), application: t("Applications", "الطلبات") };

  return <ProductShell title={t("Activity", "النشاط")} active="/dashboard/registrations"><div className="workspace-route-page activity-workspace">
    <div className="product-page-heading compact"><div><SectionLabel>{t("Workspace / Activity", "مساحة العمل / النشاط")}</SectionLabel><h1>{t("See what the work taught you.", "شاهد ما الذي علّمك إياه العمل.")}</h1><p>{t("Decisions, event commitments, and applications stay connected. Learning records show the evidence and the next return point without recreating context.", "تبقى القرارات والتزامات الفعاليات والطلبات متصلة. تُظهر سجلات التعلم الدليل ونقطة العودة التالية دون إعادة إنشاء السياق.")}</p></div><SignalTag tone="soft">{t(`${formatNum(records.length)} records`, `${formatNum(records.length)} سجلات`)}</SignalTag></div>

    <section className="activity-learning-summary" aria-labelledby="activity-learning-title"><div className="activity-learning-summary__intro"><SectionLabel>{t("Decision learning", "تعلم القرار")}</SectionLabel><h2 id="activity-learning-title">{t("Keep the signal, not just the file.", "احتفظ بالإشارة لا بالملف فقط.")}</h2><p>{t("Review outcomes stay beside the evidence, owner, and next action that gave each decision its shape.", "تبقى نتائج المراجعة بجانب الدليل والمالك والخطوة التالية التي أعطت كل قرار شكله.")}</p></div><div className="activity-learning-summary__metrics"><div><span>{t("Saved", "محفوظة")}</span><strong>{formatNum(decisions.length)}</strong></div><div><span>{t("Learned", "تم التعلم")}</span><strong>{formatNum(learnedDecisions.length)}</strong></div><div><span>{t("Open review", "مراجعة مفتوحة")}</span><strong>{formatNum(openDecisions.length)}</strong></div></div><Link href="/dashboard/decision-review" className="button button-dark">{t("Review decisions", "راجع القرارات")} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</Link></section>

    {decisions.length > 0 && <section className="activity-learning-ledger" aria-label={t("Decision learning ledger", "سجل تعلم القرار")}><div className="activity-learning-ledger__heading"><div><SectionLabel>{t("Learning ledger", "سجل التعلم")}</SectionLabel><h2>{t("The latest useful evidence.", "أحدث الأدلة المفيدة.")}</h2></div><Link href="/dashboard/decision-review" className="text-link">{t("Open full review", "افتح المراجعة الكاملة")} {isRTL ? <ArrowLeft size={13} /> : <ArrowRight size={13} />}</Link></div><div className="activity-learning-records">{decisions.slice(0, 3).map((record) => <article key={record.id}><header><span className={record.outcome ? "is-complete" : ""}>{record.outcome ? <Check size={13} /> : t("OPEN", "مفتوح")}</span><strong>{outcomeLabel(record)}</strong></header><h3>{t(record.title, record.titleAr)}</h3><p className="activity-learning-records__evidence">{record.evidence || t("No evidence recorded yet. Return while the customer language or result is still specific.", "لم يُسجل دليل بعد. عد بينما تظل لغة العميل أو النتيجة محددة.")}</p><dl><div><dt>{t("Owner", "المالك")}</dt><dd>{t(record.owner ?? "Founder", record.ownerAr ?? "المؤسس")}</dd></div><div><dt>{t("Next action", "الخطوة التالية")}</dt><dd>{t(record.nextAction ?? "Choose the next action", record.nextActionAr ?? "اختر الخطوة التالية")}</dd></div><div><dt>{t("Review", "المراجعة")}</dt><dd>{t(record.reviewDate ?? "Review after 7 days", record.reviewDateAr ?? "راجع بعد ٧ أيام")}</dd></div></dl><Link href="/dashboard/decision-review" className="text-link">{record.outcome ? t("Review learning", "راجع التعلم") : t("Record learning", "سجل التعلم")} {isRTL ? <ArrowLeft size={13} /> : <ArrowRight size={13} />}</Link></article>)}</div></section>}

    <div className="request-tabs" role="toolbar" aria-label={t("Filter workspace activity", "تصفية نشاط مساحة العمل")}>{(["all", "decision", "event", "application"] as ActivityFilter[]).map((kind) => <button type="button" key={kind} className={filter === kind ? "active" : ""} aria-pressed={filter === kind} onClick={() => setFilter(kind)}>{labels[kind]}</button>)}</div>
    {shown.length ? <div className="receipt-list">{shown.map((record) => <article key={record.id} className={reviewed[record.id] ? "is-reviewed" : ""}><div><span className="mono">{reviewed[record.id] ? t("REVIEWED", "تمت المراجعة") : record.kind === "decision" && record.outcome ? t(`DECISION / ${outcomeLabel(record).toUpperCase()}`, `قرار / ${outcomeLabel(record)}`) : t(`${record.kind.toUpperCase()} / ${record.status.toUpperCase()}`, `${record.kind === "decision" ? "قرار" : record.kind === "event" ? "فعالية" : "طلب"} / ${record.status === "submitted" ? "مقدم" : record.status === "registered" ? "مسجل" : "محفوظ"}`)}</span><h2>{t(record.title, record.titleAr)}</h2><p>{record.kind === "decision" ? record.evidence ? t(`Learning: ${record.evidence}`, `التعلم: ${record.evidence}`) : t("Return to record the evidence before the next conversation makes it less specific.", "عد لتسجيل الدليل قبل أن تجعل المحادثة التالية تفاصيله أقل تحديدا.") : record.kind === "event" ? t("Keep the event close with a calendar handoff or reminder.", "أبقِ الفعالية قريبة عبر إضافة للتقويم أو تذكير.") : t("Your brief is in review. Return to it if the route asks for more context.", "موجزك قيد المراجعة. عد إليه إذا طلب المسار مزيدا من السياق.")}</p></div><div className="activity-row-actions">{record.kind === "decision" ? <Link href="/dashboard/decision-review" className="button button-ghost">{record.outcome ? t("Review", "مراجعة") : t("Record learning", "سجل التعلم")} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</Link> : <Link href={record.href} className="button button-ghost">{t("Open", "افتح")} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</Link>}{record.kind === "event" && <button type="button" className="button button-light" aria-pressed={followUps[record.id] ?? false} onClick={() => setFollowUps((current) => ({ ...current, [record.id]: !current[record.id] }))}><CalendarPlus size={14} /> {followUps[record.id] ? t("Follow-up set", "تم ضبط المتابعة") : t("Set follow-up", "اضبط المتابعة")}</button>}<button type="button" className="text-link" onClick={() => setReviewed((current) => ({ ...current, [record.id]: !current[record.id] }))}>{reviewed[record.id] ? t("Reopen", "أعد الفتح") : t("Mark reviewed", "علِّم كمراجَع")}</button><button type="button" className="text-link" onClick={() => clear(record.id)}>{t("Remove", "إزالة")}</button></div></article>)}</div> : <div className="empty-state compact-empty"><h2>{t("Your activity will collect here.", "سيتجمع نشاطك هنا.")}</h2><p>{t("Save a decision, keep an event, or submit an application to create a useful record you can return to.", "احفظ قرارا أو احتفظ بفعالية أو قدم طلبا لإنشاء سجل مفيد تعود إليه.")}</p><Link href="/tools" className="button button-dark">{t("Open founder tools", "افتح أدوات المؤسس")}</Link></div>}
  </div></ProductShell>;
}
