/* Landing-derived matching experience: asymmetrical map, evidence-led founder signals, and structured introductions. */
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, MapPin, Network, Search, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { SectionLabel, SignalTag } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";

const people = [
  { id: 1, initials: "NH", name: "Nour Haddad", role: "Founder, B2B SaaS · Amman", copy: "Building repeatable sales motion after the first ten customers.", tag: "GTM", arRole: "مؤسسة برمجيات B2B · عمان", arCopy: "تبني حركة مبيعات قابلة للتكرار بعد أول عشرة عملاء.", arTag: "نمو السوق" },
  { id: 2, initials: "OA", name: "Omar Al-Khatib", role: "Product operator · Dubai", copy: "Has shipped pricing changes across two regional SaaS teams.", tag: "Pricing", arRole: "مشغل منتجات · دبي", arCopy: "قاد تغييرات التسعير في فريقين إقليميين للبرمجيات.", arTag: "التسعير" },
  { id: 3, initials: "LS", name: "Layla Saad", role: "People lead · Riyadh", copy: "Hiring the first layer of operators without losing the founder pace.", tag: "Hiring", arRole: "قائدة فريق · الرياض", arCopy: "توظف أول طبقة من المشغلين دون فقدان إيقاع المؤسس.", arTag: "التوظيف" },
  { id: 4, initials: "YK", name: "Youssef Khalil", role: "Founder, workflow SaaS · Cairo", copy: "Learning how to expand from Egypt into the Gulf with focus.", tag: "Expansion", arRole: "مؤسس برمجيات سير عمل · القاهرة", arCopy: "يتعلم كيف يتوسع من مصر إلى الخليج بتركيز.", arTag: "التوسع" },
  { id: 5, initials: "MA", name: "Maha Al-Sayed", role: "Mentor · Manama", copy: "Former revenue lead for startups finding their first repeatable channel.", tag: "Revenue", arRole: "مرشدة · المنامة", arCopy: "قائدة إيرادات سابقة تساعد الشركات الناشئة على إيجاد أول قناة قابلة للتكرار.", arTag: "الإيرادات" },
  { id: 6, initials: "FS", name: "Fadi Saad", role: "Founder, fintech SaaS · Beirut", copy: "Open to sharing the messy version of fundraising and runway planning.", tag: "Fundraising", arRole: "مؤسس برمجيات مالية · بيروت", arCopy: "مستعد لمشاركة الجانب المعقد من جمع التمويل وتخطيط المدرج المالي.", arTag: "جمع التمويل" },
];

const focusOptions = ["All", "Pricing", "Hiring", "Expansion"] as const;
const stageOptions = ["Idea", "First revenue", "Growth"] as const;

export default function Connect() {
  const { t, formatNum, isRTL } = useLocale();
  const [query, setQuery] = useState("");
  const [focus, setFocus] = useState<(typeof focusOptions)[number]>("All");
  const [stage, setStage] = useState<(typeof stageOptions)[number]>("Idea");
  const displayPeople = people.map((person) => ({ ...person, role: t(person.role, person.arRole), copy: t(person.copy, person.arCopy), tag: t(person.tag, person.arTag), rawTag: person.tag }));
  const filtered = useMemo(() => displayPeople.filter((person) => `${person.name} ${person.role} ${person.copy} ${person.tag}`.toLowerCase().includes(query.toLowerCase()) && (focus === "All" || person.rawTag === focus)), [query, focus, displayPeople]);
  const stageArabic: Record<(typeof stageOptions)[number], string> = { Idea: "فكرة", "First revenue": "أول إيراد", Growth: "نمو" };
  const focusArabic: Record<(typeof focusOptions)[number], string> = { All: "كل المسارات", Pricing: "التسعير", Hiring: "التوظيف", Expansion: "التوسع" };
  const direction = isRTL ? <ArrowLeft size={15} /> : <ArrowRight size={15} />;

  return <>
    <section className="connect-map-hero">
      <div className="container connect-map-hero__inner">
        <div className="connect-map-copy">
          <SectionLabel light>{t("Connect / Founder matching", "تواصل / مطابقة المؤسسين")}</SectionLabel>
          <h1>{t("Your next useful introduction is already inside the network.", "مقدمتك المفيدة التالية موجودة بالفعل داخل الشبكة.")}</h1>
          <p>{t("Describe the real friction in front of you. ASaaSI surfaces the founder, operator, or specialist with enough context to make the first conversation worth having.", "صف الاحتكاك الحقيقي أمامك. يكشف أساسي المؤسس أو المشغل أو المتخصص الذي يملك سياقا كافيا لجعل المحادثة الأولى تستحق أن تبدأ.")}</p>
          <div className="connect-map-copy__actions"><Link href="/requests/new" className="button button-primary">{t("Build a matching brief", "أنشئ موجز مطابقة")} {direction}</Link><a href="#match-slate" className="text-link light">{t("Browse the slate", "تصفح قائمة التطابقات")} <ArrowUpRight size={15} /></a></div>
          <div className="connect-hero-brief-rail" aria-label={t("Matching brief summary", "ملخص موجز المطابقة")}><div><span>{formatNum("01")}</span><strong>{t("Name the friction", "سمِ الاحتكاك")}</strong><small>{t("What decision is blocked?", "أي قرار متعطل؟")}</small></div><div><span>{formatNum("02")}</span><strong>{t("Add the context", "أضف السياق")}</strong><small>{t("Stage, market, and path tried.", "المرحلة والسوق والمسار المجرّب.")}</small></div><div><span>{formatNum("03")}</span><strong>{t("Open the route", "افتح المسار")}</strong><small>{t("One person with a reason to reply.", "شخص واحد يملك سببا للرد.")}</small></div></div>
          <div className="connect-proofline"><span><i />{t("Curated introductions", "مقدمات منتقاة")}</span><span><i />{t("Context before chemistry", "السياق قبل الانسجام")}</span><span><i />{t("One clear next move", "خطوة تالية واضحة")}</span></div>
        </div>
        <div className="connect-orbit" aria-label={t("Connection map preview", "معاينة خريطة الاتصالات")}>
          <div className="connect-orbit__mesh" aria-hidden="true"><i className="mesh-one" /><i className="mesh-two" /><i className="mesh-three" /><i className="mesh-four" /></div>
          <div className="connect-orbit__core"><Network size={22} /><span>{t("YOUR ASK", "طلبك")}</span></div>
          {people.slice(0, 4).map((person, index) => <div className={`connect-orbit__person orbit-person-${index + 1}`} key={person.id}><span>{person.initials}</span><div><strong>{person.name}</strong><small>{t(person.tag, person.arTag)}</small></div></div>)}
          <div className="connect-orbit__signal"><Sparkles size={14} /><span>{t("4 possible routes", "٤ مسارات محتملة")}</span></div>
        </div>
      </div>
      <div className="container"><div className="connect-brief-builder">
        <div className="connect-brief-builder__title"><span className="connect-step-number">{formatNum("01")}</span><div><span className="mono">{t("MATCHING BRIEF", "موجز المطابقة")}</span><strong>{t("Give the network a useful starting point.", "امنح الشبكة نقطة بداية مفيدة.")}</strong></div></div>
        <div className="connect-brief-builder__fields"><div><span className="mono">{t("WHAT NEEDS TO MOVE?", "ما الذي يحتاج إلى التحرك؟")}</span><div className="connect-choice-row">{focusOptions.map((option) => <button type="button" className={focus === option ? "is-selected" : ""} key={option} onClick={() => setFocus(option)}>{t(option, focusArabic[option])}</button>)}</div></div><div><span className="mono">{t("WHERE ARE YOU NOW?", "أين تقف الآن؟")}</span><div className="connect-choice-row">{stageOptions.map((option) => <button type="button" className={stage === option ? "is-selected" : ""} key={option} onClick={() => setStage(option)}>{t(option, stageArabic[option])}</button>)}</div></div></div>
        <div className="connect-brief-builder__status"><span><i />{t("Signal set", "تم تحديد الإشارة")}: {t(stage, stageArabic[stage])} / {t(focus, focusArabic[focus])}</span><a href="#match-slate">{t("See matching people", "شاهد الأشخاص المناسبين")} {direction}</a></div>
      </div></div>
    </section>

    <section className="connect-method-section"><div className="container"><div className="connect-method-heading"><div><SectionLabel>{t("The introduction method", "منهج المقدمة")}</SectionLabel><h2>{t("The ask gets sharper before the network gets bigger.", "يصبح الطلب أكثر دقة قبل أن تصبح الشبكة أكبر.")}</h2></div><p>{t("One real decision, enough operating context, and a reason the next person can reply. That is the whole matching method.", "قرار حقيقي وسياق تشغيلي كاف وسبب يستطيع الشخص التالي الرد عليه. هذا هو منهج المطابقة كاملا.")}</p></div><ol className="connect-method"><li><span>{formatNum("01")}</span><div><small>{t("NAME THE FRICTION", "سمِ الاحتكاك")}</small><strong>{t("What has stopped moving?", "ما الذي توقف عن التحرك؟")}</strong></div></li><li><span>{formatNum("02")}</span><div><small>{t("ADD THE CONTEXT", "أضف السياق")}</small><strong>{t("Stage, market, and the path already tried.", "المرحلة والسوق والمسار الذي جُرّب بالفعل.")}</strong></div></li><li><span>{formatNum("03")}</span><div><small>{t("MAKE THE HANDOFF", "اصنع الإحالة")}</small><strong>{t("One person with a reason to start.", "شخص واحد يملك سببا للبدء.")}</strong></div></li></ol></div></section>

    <section className="connect-slate-section" id="match-slate"><div className="container connect-slate-layout"><aside className="connect-filter-panel"><div><SectionLabel>{t("Match controls", "عناصر المطابقة")}</SectionLabel><h3>{t("Keep the filter close to the question.", "أبقِ الفلتر قريبا من السؤال.")}</h3></div><div className="connect-filter-group"><span>{t("Focus", "المسار")}</span>{focusOptions.slice(1).map((option) => <button type="button" className={focus === option ? "is-active" : ""} key={option} onClick={() => setFocus(option)}><i />{t(option, focusArabic[option])}</button>)}</div><div className="connect-filter-group"><span>{t("Market", "السوق")}</span><button type="button"><i />{t("GCC", "الخليج")}</button><button type="button"><i />{t("Egypt", "مصر")}</button><button type="button"><i />{t("Levant", "المشرق")}</button></div><Link href="/requests/new" className="button button-dark button-small">{t("Write a matching brief", "اكتب موجز مطابقة")} {direction}</Link></aside><div className="connect-slate-main"><div className="connect-slate-heading"><div><SectionLabel>{t("The match slate", "قائمة التطابقات")}</SectionLabel><h2>{formatNum(filtered.length)} {t("people with useful context", "أشخاص يملكون سياقا مفيدا")}</h2><p>{t("These profiles show the operating reason to connect, not just a job title.", "تعرض هذه الملفات السبب التشغيلي للتواصل، لا مجرد المسمى الوظيفي.")}</p></div><label className="connect-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("Search a name, market, or problem", "ابحث بالاسم أو السوق أو المشكلة")} /></label></div>{filtered.length ? <div className="connect-match-slate">{filtered.map((person, index) => <article className="connect-match-card" key={person.id}><div className="connect-match-card__index">{formatNum(index + 1)}</div><div className="connect-match-card__identity"><span className="connect-match-avatar">{person.initials}</span><div><h3>{person.name}</h3><p><MapPin size={12} /> {person.role}</p></div></div><div className="connect-match-card__reason"><span className="mono">{t("WHY THIS MATCH", "سبب هذا التطابق")}</span><p>{person.copy}</p></div><div className="connect-match-card__action"><SignalTag tone="soft">{person.tag}</SignalTag><Link href={`/members/${person.id}`} className="button button-ghost button-small">{t("Request intro", "اطلب مقدمة")} <ArrowUpRight size={14} /></Link></div></article>)}</div> : <div className="connect-empty"><SignalTag>{t("No exact match in this slate", "لا تطابق دقيق في القائمة")}</SignalTag><h3>{t("Describe the question instead.", "صف السؤال بدلا من ذلك.")}</h3><p>{t("The network is more useful when founders name the actual blocker, not just the category.", "تكون الشبكة أكثر فائدة عندما يحدد المؤسسون العائق الحقيقي، لا الفئة فقط.")}</p><Link href="/requests/new" className="button button-dark">{t("Create the request", "أنشئ الطلب")} {direction}</Link></div>}</div></div></section>

    <section className="connect-closing"><div className="container"><div><SectionLabel light>{t("One introduction starts free", "مقدمة واحدة تبدأ مجانا")}</SectionLabel><h2>{t("The right person is more useful than another open tab.", "الشخص المناسب أكثر فائدة من علامة تبويب مفتوحة أخرى.")}</h2></div><div><p>{t("Join free, write one focused ask, and let the network connect it to the context already here.", "انضم مجانا، واكتب طلبا مركزا، ودع الشبكة تصله بالسياق الموجود بالفعل هنا.")}</p><div><Link href="/signup" className="button button-primary">{t("Join free", "انضم مجانا")} {direction}</Link><Link href="/pricing" className="button button-ghost">{t("See membership", "شاهد العضوية")}</Link></div></div></div></section>
  </>;
}
