/* Editorial Operating System, bilingual event discovery is an editorial decision path: lead event, context rail, filtered outcomes. */
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Bookmark, CalendarDays, MapPin, SlidersHorizontal } from "lucide-react";
import { Link, useLocation } from "wouter";
import { PageIntro, SectionLabel, SignalTag, Toast, useToast } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";
import { useAuth } from "../contexts/AuthContext";
import { upsertWorkflowRecord } from "../lib/workflowRecords";

export const monthAr: Record<string, string> = { SEP: "سبتمبر", OCT: "أكتوبر", NOV: "نوفمبر", DEC: "ديسمبر", JAN: "يناير", FEB: "فبراير", MAR: "مارس", APR: "أبريل", MAY: "مايو", JUN: "يونيو", JUL: "يوليو", AUG: "أغسطس" };
const eventIntents = ["All events", "Pricing", "Hiring", "Expansion", "Peers"] as const;
const intentArabic: Record<(typeof eventIntents)[number], string> = { "All events": "كل الفعاليات", Pricing: "التسعير", Hiring: "التوظيف", Expansion: "التوسع", Peers: "الأقران" };
export const events = [
  { slug: "founder-briefing", intent: "Pricing", day: "18", month: "SEP", title: "Founder Briefing: when growth gets noisy", copy: "A practical evening for pricing, hiring, and the next market.", meta: "18 Sep · 18:30 GST", tag: "Featured", href: "/events/founder-briefing", outcome: "Leave with a sharper offer", location: "Dubai + online", price: null as number | null, seats: 24, arTitle: "إحاطة المؤسس: عندما يصبح النمو مشوشا", arCopy: "أمسية عملية للتسعير والتوظيف والسوق التالي.", arTag: "فعالية مختارة", arOutcome: "غادر بعرض أوضح", arLocation: "دبي + عبر الإنترنت" },
  { slug: "operator-room", intent: "Hiring", day: "24", month: "SEP", title: "Operator Workshop: the first repeatable sales motion", copy: "A small-group working session for early revenue teams.", meta: "24 Sep · 17:00 EET", tag: "Small group", href: "/events/operator-room", outcome: "Name the next sales experiment", location: "Online · 12 seats", price: null as number | null, seats: 12, arTitle: "ورشة المشغلين: أول حركة مبيعات قابلة للتكرار", arCopy: "جلسة عمل لمجموعة صغيرة من فرق الإيرادات المبكرة.", arTag: "مجموعة صغيرة", arOutcome: "سمِ تجربة المبيعات التالية", arLocation: "عبر الإنترنت · ١٢ مقعدا" },
  { slug: "cairo-founder-circle", intent: "Peers", day: "02", month: "OCT", title: "Cairo Founder Circle: what are you saying no to?", copy: "An offline circle for founders in the city building through the next decision.", meta: "02 Oct · 19:00 EET", tag: "Cairo", href: "/events/cairo-founder-circle", outcome: "Trade one honest pattern", location: "Cairo · in person", price: null as number | null, seats: 20, arTitle: "دائرة مؤسسي القاهرة: ما الذي تقول له لا؟", arCopy: "دائرة حضورية لمؤسسي المدينة وهم يبنون القرار التالي.", arTag: "القاهرة", arOutcome: "تبادل نمط صادق واحد", arLocation: "القاهرة · حضوري" },
  { slug: "saas-summit-mena-2026", intent: "Expansion", day: "12", month: "NOV", title: "SaaS Summit MENA 2026", copy: "Two days with the operators building the region's most useful software companies.", meta: "12-13 Nov · Dubai", arMeta: "١٢-١٣ نوفمبر · دبي", tag: "Summit", href: "/events/saas-summit-mena-2026", outcome: "Leave with three useful conversations", location: "Dubai · in person", price: 149 as number | null, seats: 84, arTitle: "قمة البرمجيات في المنطقة ٢٠٢٦", arCopy: "يومان مع المشغلين الذين يبنون أكثر شركات البرمجيات فائدة في المنطقة.", arTag: "قمة", arOutcome: "غادر بثلاث محادثات مفيدة", arLocation: "دبي · حضوري" }
];

const pastEvents = [
  { title: "Cairo Founder Circle: pricing after the first 10 customers", arTitle: "دائرة مؤسسي القاهرة: التسعير بعد أول ١٠ عملاء", date: "14 Jul 2026", dateAr: "١٤ يوليو ٢٠٢٦", attendees: 32 },
  { title: "Operator Workshop: the leaky-bucket audit", arTitle: "ورشة المشغلين: تدقيق التسرب", date: "22 Jun 2026", dateAr: "٢٢ يونيو ٢٠٢٦", attendees: 18 },
  { title: "Founder Briefing: hiring without a recruiter", arTitle: "إحاطة المؤسس: التوظيف بلا مسؤول توظيف", date: "05 May 2026", dateAr: "٥ مايو ٢٠٢٦", attendees: 41 }
];

export default function Events() {
  const { t, formatNum, isRTL } = useLocale();
  const { isAuthed } = useAuth();
  const [, setLocation] = useLocation();
  const { message, showToast, clearToast } = useToast();
  const [intent, setIntent] = useState<(typeof eventIntents)[number]>("All events");
  const filteredEvents = useMemo(() => intent === "All events" ? events : events.filter((event) => event.intent === intent), [intent]);
  const displayEvents = filteredEvents.map((event) => {
    const month = t(event.month, monthAr[event.month] ?? event.month);
    const timeAndZone = event.meta.match(/(\d{1,2}:\d{2}) (\w+)/);
    const meta = "arMeta" in event ? t(event.meta, event.arMeta as string) : timeAndZone ? `${formatNum(event.day)} ${month} · ${formatNum(timeAndZone[1])} ${timeAndZone[2]}` : event.meta;
    return { ...event, day: formatNum(event.day), month, meta, title: t(event.title, event.arTitle), copy: t(event.copy, event.arCopy), tag: t(event.tag, event.arTag), outcome: t(event.outcome, event.arOutcome), location: t(event.location, event.arLocation) };
  });
  const saveEvent = () => { if (!isAuthed) { setLocation("/signup?intent=save-event"); return; } upsertWorkflowRecord({ id: `event-${events[0].slug}`, kind: "event", title: events[0].title, titleAr: events[0].arTitle, href: events[0].href, status: "registered" }); showToast(t("Founder Briefing saved to your workspace activity.", "تم حفظ إحاطة المؤسس في نشاط مساحة عملك.")); };
  useEffect(() => { const id = window.location.hash.replace("#", ""); if (id) document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }, []);
  return <>
    <PageIntro label={t("Meet / Events", "التقِ / فعاليات")} title={t("Events worth making time for.", "فعاليات تستحق أن تُخصَص لها وقتا.")} copy={t("The founders, mentors, and specialists in this ecosystem meet in person and online, all across MENA. Browse by goal, and know what you'll leave with before you register, free to attend, one quick signup to save your seat.", "المؤسسون والمرشدون والمتخصصون في هذه المنظومة يلتقون حضوريا وعبر الإنترنت، في أنحاء المنطقة. تصفح حسب الهدف، واعرف ما ستخرج به قبل التسجيل، الحضور مجاني، وتسجيل سريع واحد لحجز مقعدك.")} />
    <section className="event-landing-feature"><div className="container"><article className="event-landing-feature__image"><img src="/manus-storage/asaasi-events-founder-gathering_97f3c5f6.jpg" alt={t("Founders in a focused working session", "مؤسسون في جلسة عمل مركزة")} /><div className="event-landing-feature__wash" aria-hidden="true" /><div className="event-landing-feature__card"><div className="event-landing-feature__date"><strong>{formatNum(events[0].day)}</strong><span>{t(events[0].month, monthAr[events[0].month] ?? events[0].month)}</span></div><div className="event-landing-feature__copy"><SectionLabel>{t("Featured founder briefing", "إحاطة مؤسس مختارة")}</SectionLabel><h2>{t(events[0].title, events[0].arTitle)}</h2><p>{t("A focused evening for founders deciding what to price, what to test, and what not to chase yet.", "أمسية مركزة للمؤسسين الذين يقررون ما الذي يسعرونه وما الذي يختبرونه وما الذي لا يلاحقونه بعد.")}</p><div className="event-landing-feature__meta"><span><CalendarDays size={13} /> {formatNum(events[0].day)} {t(events[0].month, monthAr[events[0].month] ?? events[0].month)} · {formatNum("18:30")} GST</span><span><MapPin size={13} /> {t(events[0].location, events[0].arLocation)}</span></div></div><div className="event-landing-feature__actions"><Link href={events[0].href} className="button button-primary">{t("View event", "شاهد الفعالية")} {isRTL ? <ArrowLeft size={15} /> : <ArrowRight size={15} />}</Link><button type="button" className="button button-light" onClick={saveEvent}><Bookmark size={14} /> {t("Save", "احفظ")}</button></div></div></article></div></section>
    <section className="section event-directory-section"><div className="container"><div className="section-header"><div><SectionLabel>{t("Browse events", "تصفح الفعاليات")}</SectionLabel><h2>{t("Choose by the work you want to move.", "اختر حسب العمل الذي تريد تحريكه.")}</h2></div><p>{t("See the topic, setting, and practical takeaway before you reserve time for it.", "شاهد الموضوع والمكان والخلاصة العملية قبل أن تخصص لها وقتا.")}</p></div><div className="event-intent-controls" role="toolbar" aria-label={t("Filter events by founder decision", "تصفية الفعاليات حسب قرار المؤسس")}><SlidersHorizontal size={16} /><span className="mono">{t("Filter", "تصفية")}</span>{eventIntents.map((option) => <button type="button" key={option} className={intent === option ? "is-active" : ""} aria-pressed={intent === option} onClick={() => setIntent(option)}>{t(option, intentArabic[option])}</button>)}</div><div className="event-results-summary"><span className="mono">{formatNum(displayEvents.length)} {t(displayEvents.length === 1 ? "event" : "events", displayEvents.length === 1 ? "فعالية" : "فعاليات")} {t("available", "متاحة")}</span><span>{t("Ordered by date.", "مرتبة حسب التاريخ.")}</span></div><div className="event-timeline" role="list">{displayEvents.map((event, index) => <Link href={event.href} key={event.title} className={`event-timeline-row ${index === 0 ? "is-next" : ""}`} role="listitem"><div className="event-timeline-date"><strong>{event.day}</strong><span>{event.month}</span></div><div className="event-timeline-main"><SignalTag tone="soft">{event.tag}</SignalTag><h3>{event.title}</h3><p>{event.copy}</p><span className="event-takeaway">{t("Takeaway", "الخلاصة")} <strong>{event.outcome}</strong></span></div><div className="event-timeline-meta"><span><CalendarDays size={14} /> {event.meta}</span><span><MapPin size={14} /> {event.location}</span><span>{event.seats ? `${formatNum(event.seats)} ${t("seats", "مقعدا")}` : t("Details coming soon", "التفاصيل قريبا")}</span></div><ArrowUpRight className="event-timeline-arrow" size={19} aria-hidden="true" /></Link>)}</div></div></section>
    <section className="section section-clay" id="past"><div className="container"><div className="section-header"><div><SectionLabel>{t("Past events", "فعاليات سابقة")}</SectionLabel><h2>{t("What already happened, for context.", "ما حدث بالفعل، للسياق.")}</h2></div><Link href="/stories" className="section-link">{t("Read the recaps", "اقرأ الملخصات")} <span>→</span></Link></div><div className="past-events-list">{pastEvents.map((event) => <div className="past-event-row" key={event.title}><SignalTag tone="soft">{t("Completed", "منتهية")}</SignalTag><div><strong>{t(event.title, event.arTitle)}</strong><span>{t(event.date, event.dateAr)} · {t(`${event.attendees} attended`, `حضرها ${formatNum(event.attendees)}`)}</span></div></div>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-header"><div><SectionLabel>{t("Host an event", "استضف فعالية")}</SectionLabel><h2>{t("Have a useful conversation to convene?", "هل لديك محادثة مفيدة لتجمعها؟")}</h2></div><Link href="/events/host" className="button button-dark">{t("Submit an event", "أرسل فعالية")} {isRTL ? <ArrowLeft size={15} /> : <ArrowRight size={15} />}</Link></div></div></section>
    {message && <Toast message={message} onClose={clearToast} />}
  </>;
}
