/* Editorial Operating System, bilingual event discovery is an editorial decision path: lead event, context rail, filtered outcomes. */
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, SlidersHorizontal } from "lucide-react";
import { Link, useLocation } from "wouter";
import { EventCard, PageIntro, SectionLabel, SignalTag, Toast, useToast } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";
import { useAuth } from "../contexts/AuthContext";

export const monthAr: Record<string, string> = { SEP: "سبتمبر", OCT: "أكتوبر", NOV: "نوفمبر", DEC: "ديسمبر", JAN: "يناير", FEB: "فبراير", MAR: "مارس", APR: "أبريل", MAY: "مايو", JUN: "يونيو", JUL: "يوليو", AUG: "أغسطس" };
const eventIntents = ["All events", "Pricing", "Hiring", "Expansion", "Peers"] as const;
const intentArabic: Record<(typeof eventIntents)[number], string> = { "All events": "كل الفعاليات", Pricing: "التسعير", Hiring: "التوظيف", Expansion: "التوسع", Peers: "الأقران" };
export const events = [
  { slug: "founder-briefing", intent: "Pricing", day: "18", month: "SEP", title: "Founder Briefing: when growth gets noisy", copy: "A practical evening for pricing, hiring, and the next market.", meta: "18 Sep · 18:30 GST", tag: "Featured", href: "/events/founder-briefing", outcome: "Leave with a sharper offer", location: "Dubai + online", price: null as number | null, seats: 24, arTitle: "إحاطة المؤسس: عندما يصبح النمو مشوشا", arCopy: "أمسية عملية للتسعير والتوظيف والسوق التالي.", arTag: "فعالية مختارة", arOutcome: "غادر بعرض أوضح", arLocation: "دبي + عبر الإنترنت" },
  { slug: "operator-room", intent: "Hiring", day: "24", month: "SEP", title: "Operator Workshop: the first repeatable sales motion", copy: "A small-group working session for early revenue teams.", meta: "24 Sep · 17:00 EET", tag: "Small group", href: "/events/operator-room", outcome: "Name the next sales experiment", location: "Online · 12 seats", price: null as number | null, seats: 12, arTitle: "ورشة المشغلين: أول حركة مبيعات قابلة للتكرار", arCopy: "جلسة عمل لمجموعة صغيرة من فرق الإيرادات المبكرة.", arTag: "مجموعة صغيرة", arOutcome: "سمِ تجربة المبيعات التالية", arLocation: "عبر الإنترنت · ١٢ مقعدا" },
  { slug: "cairo-founder-circle", intent: "Peers", day: "02", month: "OCT", title: "Cairo Founder Circle: what are you saying no to?", copy: "An offline circle for founders in the city building through the next decision.", meta: "02 Oct · 19:00 EET", tag: "Cairo", href: "/events/cairo-founder-circle", outcome: "Trade one honest pattern", location: "Cairo · in person", price: null as number | null, seats: 20, arTitle: "دائرة مؤسسي القاهرة: ما الذي تقول له لا؟", arCopy: "دائرة حضورية لمؤسسي المدينة وهم يبنون القرار التالي.", arTag: "القاهرة", arOutcome: "تبادل نمط صادق واحد", arLocation: "القاهرة · حضوري" },
  { slug: "saas-summit-mena-2026", intent: "Expansion", day: "12", month: "NOV", title: "SaaS Summit MENA 2026", copy: "Two days with the operators building the region's most useful software companies.", meta: "12-13 Nov · Dubai", arMeta: "١٢-١٣ نوفمبر · دبي", tag: "Summit", href: "/events/saas-summit-mena-2026", outcome: "Leave with three useful conversations", location: "Dubai · in person", price: 149 as number | null, seats: 84, arTitle: "قمة البرمجيات في المنطقة ٢٠٢٦", arCopy: "يومان مع المشغلين الذين يبنون أكثر شركات البرمجيات فائدة في المنطقة.", arTag: "قمة", arOutcome: "غادر بثلاث محادثات مفيدة", arLocation: "دبي · حضوري" }
];

const pastEvents = [
  { title: "Cairo Founder Circle: pricing after the first 10 customers", arTitle: "دائرة مؤسسي القاهرة: التسعير بعد أول ١٠ عملاء", date: "14 Jul 2026", dateAr: "١٤ يوليو ٢٠٢٦", attendees: 32 },
  { title: "Operator Workshop: the leaky-bucket audit", arTitle: "ورشة المشغلين: تدقيق التسرب", date: "22 Jun 2026", dateAr: "٢٢ يونيو ٢٠٢٦", attendees: 18 },
  { title: "Founder Briefing: hiring without a recruiter", arTitle: "إحاطة المؤسس: التوظيف بلا مسؤول توظيف", date: "05 May 2026", dateAr: "٥ مايو ٢٠٢٦", attendees: 41 }
];

export default function Events() {
  const { t, formatNum, isRTL } = useLocale();
  const { isAuthed } = useAuth();
  const [, setLocation] = useLocation();
  const { message, showToast, clearToast } = useToast();
  const [intent, setIntent] = useState<(typeof eventIntents)[number]>("All events");
  const filteredEvents = useMemo(() => intent === "All events" ? events : events.filter((event) => event.intent === intent), [intent]);
  const displayEvents = filteredEvents.map((event) => {
    const month = t(event.month, monthAr[event.month] ?? event.month);
    const timeAndZone = event.meta.match(/(\d{1,2}:\d{2}) (\w+)/);
    const meta = "arMeta" in event ? t(event.meta, event.arMeta as string) : timeAndZone ? `${formatNum(event.day)} ${month} · ${formatNum(timeAndZone[1])} ${timeAndZone[2]}` : event.meta;
    return { ...event, day: formatNum(event.day), month, meta, title: t(event.title, event.arTitle), copy: t(event.copy, event.arCopy), tag: t(event.tag, event.arTag), outcome: t(event.outcome, event.arOutcome), location: t(event.location, event.arLocation) };
  });
  const saveEvent = () => { if (!isAuthed) { setLocation("/signup?intent=save-event"); return; } showToast(t("Founder Briefing saved to your shortlist.", "تم حفظ إحاطة المؤسس في قائمتك.")); };
  useEffect(() => { const id = window.location.hash.replace("#", ""); if (id) document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }, []);
  return <>
    <PageIntro label={t("Meet / Events", "التقِ / فعاليات")} title={t("Events worth making time for.", "فعاليات تستحق أن تُخصَص لها وقتا.")} copy={t("The founders, mentors, and specialists in this ecosystem meet in person and online, all across MENA. Browse by goal, and know what you'll leave with before you register, free to attend, one quick signup to save your seat.", "المؤسسون والمرشدون والمتخصصون في هذه المنظومة يلتقون حضوريا وعبر الإنترنت، في أنحاء المنطقة. تصفح حسب الهدف، واعرف ما ستخرج به قبل التسجيل، الحضور مجاني، وتسجيل سريع واحد لحجز مقعدك.")} />
    <section className="section event-pathway-section"><div className="container event-pathway-layout"><div className="event-pathway-brief"><SectionLabel>{t("The event map", "خريطة الفعالية")}</SectionLabel><h2>{t("Every event should move one decision.", "كل فعالية يجب أن تحرك قرارا واحدا.")}</h2><p>{t("Start with the question you are carrying. Choose an event with a clear outcome, then leave with one next move.", "ابدأ بالسؤال الذي تحمله. اختر فعالية بنتيجة واضحة، ثم غادر بخطوة تالية واحدة.")}</p><div className="event-pathway-index"><span className="mono">{t("01 / QUESTION", "٠١ / السؤال")}</span><strong>{t("What needs to change?", "ما الذي يحتاج إلى تغيير؟")}</strong><span className="mono">{t("02 / EVENT", "٠٢ / الفعالية")}</span><strong>{t("Who is already working it through?", "من يعمل على هذا بالفعل؟")}</strong><span className="mono">{t("03 / OUTCOME", "٠٣ / النتيجة")}</span><strong>{t("What will you do by Friday?", "ماذا ستفعل قبل الجمعة؟")}</strong></div></div><article className="event-featured-card"><div className="event-featured-top"><div className="event-date event-date-large"><strong>{formatNum(events[0].day)}</strong><span>{t(events[0].month, monthAr[events[0].month] ?? events[0].month)}</span></div><div><SignalTag>{t("Featured event", "فعالية مختارة")}</SignalTag><span className="mono">{t("Dubai + online", "دبي + عبر الإنترنت")} · {formatNum("18:30")} GST</span></div></div><h2>{t("Founder Briefing: when growth gets noisy", "إحاطة المؤسس: عندما يصبح النمو مشوشا")}</h2><p>{t("A focused session for founders deciding what to price, what to test, and what not to chase yet.", "جلسة مركزة للمؤسسين الذين يقررون ما الذي يسعرونه وما الذي يختبرونه وما الذي لا يلاحقونه بعد.")}</p><div className="event-featured-meta"><span>{t("Pricing · 24 seats", "التسعير · ٢٤ مقعدا")}</span><span>{t("Leave with a sharper offer", "غادر بعرض أوضح")}</span></div><div className="product-actions"><Link href="/events/founder-briefing" className="button button-dark">{t("View event", "شاهد الفعالية")} {isRTL ? <ArrowLeft size={15} /> : <ArrowRight size={15} />}</Link><button className="button button-light" onClick={saveEvent}>{t("Save event", "احفظ الفعالية")}</button></div></article></div></section>
    <section className="section"><div className="container"><div className="section-header"><div><SectionLabel>{t("Find your event", "اعثر على فعاليتك")}</SectionLabel><h2>{t("Browse by what you want to move.", "تصفح حسب ما تريد تحريكه.")}</h2></div><p>{t("Every event has an outcome, an audience, and a clear reason to spend the evening there.", "كل فعالية لها نتيجة وجمهور وسبب واضح لقضاء المساء فيها.")}</p></div><div className="event-intent-controls" role="toolbar" aria-label={t("Filter events by founder decision", "تصفية الفعاليات حسب قرار المؤسس")}><SlidersHorizontal size={16} /><span className="mono">{t("Filter by decision", "تصفية حسب القرار")}</span>{eventIntents.map((option) => <button type="button" key={option} className={intent === option ? "is-active" : ""} aria-pressed={intent === option} onClick={() => setIntent(option)}>{t(option, intentArabic[option])}</button>)}</div><div className="event-results-summary"><span className="mono">{displayEvents.length} {t(displayEvents.length === 1 ? "event" : "events", displayEvents.length === 1 ? "فعالية" : "فعاليات")} {t("in view", "معروضة")}</span><span>{t("Sorted by usefulness, then date.", "مرتبة حسب الفائدة ثم التاريخ.")}</span></div><div className="event-editorial-list">{displayEvents.map((event) => <EventCard key={event.title} {...event} />)}</div></div></section>
    <section className="section section-clay" id="past"><div className="container"><div className="section-header"><div><SectionLabel>{t("Past events", "فعاليات سابقة")}</SectionLabel><h2>{t("What already happened, for context.", "ما حدث بالفعل، للسياق.")}</h2></div><Link href="/stories" className="section-link">{t("Read the recaps", "اقرأ الملخصات")} <span>→</span></Link></div><div className="past-events-list">{pastEvents.map((event) => <div className="past-event-row" key={event.title}><SignalTag tone="soft">{t("Completed", "منتهية")}</SignalTag><div><strong>{t(event.title, event.arTitle)}</strong><span>{t(event.date, event.dateAr)} · {t(`${event.attendees} attended`, `حضرها ${formatNum(event.attendees)}`)}</span></div></div>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-header"><div><SectionLabel>{t("Host an event", "استضف فعالية")}</SectionLabel><h2>{t("Have a useful conversation to convene?", "هل لديك محادثة مفيدة لتجمعها؟")}</h2></div><Link href="/events/host" className="button button-dark">{t("Submit an event", "أرسل فعالية")} {isRTL ? <ArrowLeft size={15} /> : <ArrowRight size={15} />}</Link></div></div></section>
    {message && <Toast message={message} onClose={clearToast} />}
  </>;
}
