/* Editorial Operating System, bilingual learning hub for content, audio, and practical playbooks. */
/* Editorial operating system: Learn is a field guide; route labels, evidence rails, and practical next moves replace generic resource cards. */
import { useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Bookmark, Check, Headphones, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { PageIntro, ResourceCard, SectionLabel, SignalTag, Toast, useToast } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";
import { useAuth } from "../contexts/AuthContext";
const deskImage = "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=1400&q=85";

const quizQuestions = [
  { key: "blocker", q: "What's blocking you most right now?", qAr: "ما الذي يعيقك أكثر الآن؟", options: [
    { label: "Pricing", labelAr: "التسعير", stage: "Validation", stageAr: "التحقق", href: "/articles/pricing-is-a-promise", resource: "Pricing is a promise, not a page.", resourceAr: "التسعير وعد، وليس صفحة." },
    { label: "Growth channels", labelAr: "قنوات النمو", stage: "Acquisition & Distribution", stageAr: "الاكتساب والتوزيع", href: "/playbooks", resource: "Distribution without a paid budget.", resourceAr: "التوزيع بلا ميزانية إعلانات." },
    { label: "Hiring", labelAr: "التوظيف", stage: "Scalability & Growth", stageAr: "قابلية التوسع والنمو", href: "/webinars/hiring-first-ten", resource: "Hiring your first ten operators.", resourceAr: "توظيف أول عشرة مشغلين." },
    { label: "Fundraising", labelAr: "جمع التمويل", stage: "Governance", stageAr: "الحوكمة", href: "/webinars/fundraising-honest-version", resource: "The honest version of fundraising.", resourceAr: "النسخة الصادقة من جمع التمويل." },
  ] },
];

const roadmapStages = [
  { stage: "Validation", stageAr: "التحقق" }, { stage: "MVP", stageAr: "النسخة الأولية" }, { stage: "Acquisition & Distribution", stageAr: "الاكتساب والتوزيع" }, { stage: "Customer Retention", stageAr: "الاحتفاظ بالعملاء" }, { stage: "Product Focus", stageAr: "تركيز المنتج" }, { stage: "Scalability & Growth", stageAr: "قابلية التوسع والنمو" }, { stage: "Governance", stageAr: "الحوكمة" }
];
const pillars = [
  { name: "Marketing", nameAr: "التسويق" }, { name: "Sales", nameAr: "المبيعات" }, { name: "Product", nameAr: "المنتج" }, { name: "Customer Success", nameAr: "نجاح العملاء" }, { name: "Finance", nameAr: "المالية" }, { name: "Legal", nameAr: "القانون" }, { name: "IT Operations", nameAr: "العمليات التقنية" }, { name: "HR & People", nameAr: "الموارد البشرية" }, { name: "Recruiting", nameAr: "التوظيف" }
];

export default function Learn() {
  const { t, formatNum, isRTL } = useLocale();
  const { isAuthed } = useAuth();
  const { message, showToast, clearToast } = useToast();
  const [quizStep, setQuizStep] = useState(0);
  const [answer, setAnswer] = useState<(typeof quizQuestions)[0]["options"][0] | null>(null);
  const [saved, setSaved] = useState(false);

  const pickAnswer = (option: (typeof quizQuestions)[0]["options"][0]) => { setAnswer(option); setQuizStep(1); };
  const saveResult = () => { if (!isAuthed) return; setSaved(true); showToast(t("Saved to your learning path.", "حُفظ في مسار تعلمك.")); };

  return <>
    <PageIntro label={t("Learn / Field guide", "تعلم / الدليل الميداني")} title={t("Good advice is specific enough to use.", "النصيحة الجيدة محددة بما يكفي لتُستخدم.")} copy={t("Short guides, founder conversations, and practical frameworks, organized around the decision in front of you.", "أدلة قصيرة ومحادثات مؤسسين وأطر عملية، منظمة حول القرار الذي أمامك.")} note={<div className="learn-hero-index"><span className="mono">{t("FIELD INDEX / ONE QUESTION", "فهرس ميداني / سؤال واحد")}</span><ol><li><b>01</b><span>{t("Name the blocker", "سمِّ العائق")}</span></li><li><b>02</b><span>{t("Read the evidence", "اقرأ الدليل")}</span></li><li><b>03</b><span>{t("Choose one move", "اختر خطوة واحدة")}</span></li></ol><p>{t("The library responds to the decision in front of you, not a generic curriculum.", "تستجيب المكتبة للقرار الذي أمامك، لا لمنهج عام.")}</p><a href="#quiz" className="button button-primary button-small">{t("Get a one-click recommendation", "احصل على توصية بنقرة واحدة")} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</a></div>} />

    <section className="section section-dark ai-experience" id="quiz"><div className="container ai-experience-grid"><div className="ai-experience-copy"><SectionLabel light><Sparkles size={13} style={{ verticalAlign: -2, marginInlineEnd: 6 }} />{t("How the guidance layer works", "كيف تعمل طبقة الإرشاد")}</SectionLabel><h2>{t("Start with the decision in front of you.", "ابدأ بالقرار الذي أمامك.")}</h2><p>{t("ASaaSI starts with your stated stage and operating question to make a practical recommendation. The full SaaS AI Coach opens as the ecosystem’s education, community, and tool data matures.", "يبدأ أساسي بمرحلتك المعلنة وسؤالك التشغيلي لتقديم توصية عملية. يفتح مرشد SaaS الكامل مع نضج بيانات التعليم والمجتمع والأدوات في المنظومة.")}</p>
      {quizStep === 0 && <div className="quiz-card"><span className="mono">{t("Pick one to get a recommendation", "اختر واحدا للحصول على توصية")}</span><h3>{t(quizQuestions[0].q, quizQuestions[0].qAr)}</h3><div className="quiz-options">{quizQuestions[0].options.map((option) => <button type="button" key={option.label} onClick={() => pickAnswer(option)}>{t(option.label, option.labelAr)} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</button>)}</div></div>}
      {quizStep === 1 && answer && <div className="quiz-card quiz-result"><span className="mono">{t("Your recommended focus", "تركيزك الموصى به")}</span><h3>{t(answer.stage, answer.stageAr)}</h3><Link href={answer.href} className="quiz-result-resource"><strong>{t(answer.resource, answer.resourceAr)}</strong>{isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</Link>{isAuthed ? <button type="button" className="button button-primary button-small" disabled={saved} onClick={saveResult}>{saved ? <><Check size={14} /> {t("Saved", "تم الحفظ")}</> : t("Save to my learning path", "احفظ في مسار تعلمي")}</button> : <Link href="/signup" className="button button-primary button-small">{t("Sign in to save this", "سجل الدخول لحفظ هذا")} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</Link>}<button type="button" className="text-link light" onClick={() => { setQuizStep(0); setAnswer(null); setSaved(false); }}>{t("Retake", "أعد المحاولة")}</button></div>}
    </div></div></section>

    <section className="section"><div className="container learning-layout"><div><img className="learning-image" src={deskImage} alt={t("Founder desk with a decision framework", "مكتب مؤسس عليه إطار قرار")} /><div style={{ marginTop: 17 }}><SignalTag tone="soft">{t("This week's brief", "موجز هذا الأسبوع")}</SignalTag><p style={{ color: "var(--muted)", lineHeight: 1.6, fontSize: 13 }}>{t("A small collection for founders choosing between more motion and better focus.", "مجموعة صغيرة للمؤسسين الذين يختارون بين حركة أكبر وتركيز أفضل.")}</p></div></div><div><div className="section-header" style={{ marginBottom: 23 }}><div><SectionLabel>{t("Curated for focus", "منتقى للتركيز")}</SectionLabel><h2>{t("Pick a useful starting point.", "اختر نقطة بداية مفيدة.")}</h2></div></div><div className="learning-list"><Link href="/playbooks" className="learning-row"><span className="mono">{t("Playbook", "دليل عملي")}</span><div><h3>{t("One focused bet", "رهان واحد مركز")}</h3><p>{t("How to choose a next move when every option looks strategically important.", "كيف تختار الخطوة التالية عندما تبدو كل الخيارات مهمة استراتيجيا.")}</p></div><span className="duration">{t("8 min", "٨ دقائق")}</span></Link><Link href="/podcasts/pricing-without-theatre" className="learning-row"><span className="mono">{t("Conversation", "محادثة")}</span><div><h3>{t("Pricing without the theatre", "التسعير بلا استعراض")}</h3><p>{t("A candid founder conversation about signal, confidence, and changing the offer.", "محادثة صريحة بين مؤسسين عن الإشارة والثقة وتغيير العرض.")}</p></div><span className="duration">{t("24 min", "٢٤ دقيقة")}</span></Link><Link href="/articles/the-good-request" className="learning-row"><span className="mono">{t("Template", "قالب")}</span><div><h3>{t("The good request", "الطلب الجيد")}</h3><p>{t("A simple structure for asking peers and mentors for the kind of help they can give.", "هيكل بسيط لطلب المساعدة التي يستطيع الأقران والمرشدون تقديمها.")}</p></div><span className="duration">{t("5 min", "٥ دقائق")}</span></Link><Link href="/articles/first-10-customers" className="learning-row"><span className="mono">{t("Guide", "دليل")}</span><div><h3>{t("First 10 customers", "أول عشرة عملاء")}</h3><p>{t("Turn early conversations into a pattern you can carry into the next month.", "حول المحادثات المبكرة إلى نمط تحمله إلى الشهر التالي.")}</p></div><span className="duration">{t("12 min", "١٢ دقيقة")}</span></Link></div></div></div></section>

    <section className="section section-clay"><div className="container"><div className="section-header"><div><SectionLabel>{t("Browse by format", "تصفح حسب الصيغة")}</SectionLabel><h2>{t("One library, fewer dead ends.", "مكتبة واحدة، طرق مسدودة أقل.")}</h2></div><p>{t("Every resource points toward a related person, event, tool, or next action.", "كل مورد يقود إلى شخص أو فعالية أو أداة أو إجراء تال ذي صلة.")}</p></div><div className="learning-list format-list">{[
      { href: "/articles/pricing-is-a-promise", tag: "Articles", tagAr: "مقالات", badge: "Open", badgeAr: "مفتوح", title: "Read the shorter path.", titleAr: "اقرأ الطريق الأقصر.", copy: "Clear notes for consequential decisions.", copyAr: "ملاحظات واضحة للقرارات المهمة.", meta: "40+ articles", metaAr: "٤٠+ مقالا" },
      { href: "/podcasts/founder-circles", tag: "Podcasts", tagAr: "بودكاست", badge: "Open", badgeAr: "مفتوح", title: "Listen on the way there.", titleAr: "استمع في الطريق.", copy: "Founder and operator conversations with transcripts.", copyAr: "محادثات مؤسسين ومشغلين مع نصوص مكتوبة.", meta: "34 episodes", metaAr: "٣٤ حلقة" },
      { href: "/videos", tag: "Videos", tagAr: "فيديوهات", badge: "Open", badgeAr: "مفتوح", title: "Watch the idea work.", titleAr: "شاهد الفكرة تعمل.", copy: "See the idea applied in the real world.", copyAr: "شاهد الفكرة مطبقة في الواقع.", meta: "22 videos", metaAr: "٢٢ فيديو" },
      { href: "/webinars", tag: "Webinars", tagAr: "ندوات", badge: "Free to attend", badgeAr: "حضور مجاني", title: "Live, with real Q&A.", titleAr: "مباشرة، مع أسئلة حقيقية.", copy: "Attend free; replays are for signed-in members.", copyAr: "الحضور مجاني؛ التسجيلات للأعضاء المسجَلين فقط.", meta: "5 upcoming", metaAr: "٥ قادمة" },
      { href: "/playbooks", tag: "Playbooks", tagAr: "أدلة عملية", badge: "Preview free", badgeAr: "معاينة مجانية", title: "Practical frameworks for the decision in front of you.", titleAr: "أطر عملية للقرار الذي أمامك.", copy: "Full download for Members.", copyAr: "التنزيل الكامل للأعضاء.", meta: "18 collections", metaAr: "١٨ مجموعة" },
      { href: "/roadmap/validation", tag: "Courses", tagAr: "الدورات", badge: "Stage 1–2 ready", badgeAr: "المرحلتان ١–٢ جاهزتان", title: "Move from proof to a usable first product.", titleAr: "انتقل من الدليل إلى منتج أول قابل للاستخدام.", copy: "Validation and MVP are ready today; future stages open as their curricula are completed.", copyAr: "التحقق والمنتج الأولي جاهزان اليوم؛ وتفتح المراحل القادمة عند اكتمال مناهجها.", meta: "7-stage roadmap", metaAr: "خارطة نمو من ٧ مراحل" },
      { href: "/workshops", tag: "Workshops", tagAr: "ورش عمل", badge: "Paid add-on", badgeAr: "إضافة مدفوعة", title: "Leave with something shipped.", titleAr: "غادر بشيء جاهز.", copy: "Facilitated, per-company, flat fee.", copyAr: "مُيسَرة، لكل شركة، برسم ثابت.", meta: "2 formats", metaAr: "صيغتان" },
    ].map((item) => <Link href={item.href} key={item.tag} className="learning-row"><span className="mono">{t(item.tag, item.tagAr)}<em className="format-badge">{t(item.badge, item.badgeAr)}</em></span><div><h3>{t(item.title, item.titleAr)}</h3><p>{t(item.copy, item.copyAr)}</p></div><span className="duration">{t(item.meta, item.metaAr)}</span></Link>)}</div></div></section>

    <section className="section section-dark"><div className="container"><div className="section-header"><div><SectionLabel light>{t("The full framework", "الإطار الكامل")}</SectionLabel><h2>{t("7 stages. 9 functions. One connected system.", "٧ مراحل. ٩ وظائف. نظام واحد متصل.")}</h2></div><p>{t("Everything in this library maps to a stage of the MENA SaaS Growth Roadmap and a functional pillar; pricing is Marketing and Finance, hiring is HR and Recruiting.", "كل ما في هذه المكتبة يرتبط بمرحلة من خارطة نمو SaaS في المنطقة ووظيفة من وظائف الشركة؛ يرتبط التسعير بالتسويق والمالية، والتوظيف بالموارد البشرية والتوظيف.")}</p></div><div className="framework-recap"><ol className="framework-recap-stages">{roadmapStages.map((s, i) => <li key={s.stage}><Link href="/roadmap/validation" style={{ display: "flex", alignItems: "center", gap: ".4rem", color: "inherit", textDecoration: "none" }}><span className="mono">{formatNum(String(i + 1).padStart(2, "0"))}</span>{t(s.stage, s.stageAr)}</Link></li>)}</ol><div className="framework-recap-pillars">{pillars.map((p) => <Link href="/playbooks" key={p.name}><span>{t(p.name, p.nameAr)}</span></Link>)}</div></div><div className="product-actions" style={{ marginTop: 22 }}><Link href="/signup" className="button button-light">{t("Create a free founder profile", "أنشئ ملف مؤسس مجانيا")} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</Link><Link href="/pricing" className="button button-primary">{t("See Subscriber access", "شاهد وصول المشترك")} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</Link></div></div></section>

    <section className="section"><div className="container"><div className="section-header"><div><SectionLabel>{t("Keep the signal", "حافظ على الإشارة")}</SectionLabel><h2>{t("Save what you want to return to.", "احفظ ما تريد العودة إليه.")}</h2></div><button className="button button-dark" onClick={() => { if (!isAuthed) { showToast(t("Sign in to save to your library.", "سجل الدخول للحفظ في مكتبتك.")); return; } showToast(t("Saved to your library.", "حُفظ في مكتبتك.")); }}><Bookmark size={15} /> {t("Save to my library", "احفظ في مكتبتي")}</button></div><div className="proof-strip proof-strip-3"><div className="proof-cell"><BookOpen size={18} /><strong style={{ marginTop: 10 }}>{t("Read", "اقرأ")}</strong><span>{t("Open the useful part without losing the thread.", "افتح الجزء المفيد دون فقدان الخيط.")}</span></div><div className="proof-cell"><Headphones size={18} /><strong style={{ marginTop: 10 }}>{t("Listen", "استمع")}</strong><span>{t("Get the conversation with a transcript when you need it.", "احصل على المحادثة مع نص مكتوب حين تحتاجه.")}</span></div><div className="proof-cell accent"><Bookmark size={18} /><strong style={{ marginTop: 10 }}>{t("Save", "احفظ")}</strong><span>{t("Keep it in your learning path, not a browser tab.", "أبقِه في مسار تعلمك، لا في تبويب متصفح.")}</span></div></div></div></section>{message && <Toast message={message} onClose={clearToast} />}</>;
}
