/* Strategy-aligned public operating model: founder-first, MENA-specific, evidence-led, and explicit about current readiness. */
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { Link } from "wouter";
import { PageIntro, SectionLabel, SignalTag } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";

const audiences = [
  { tag: ["01 / PRIMARY TODAY", "٠١ / الأولوية اليوم"], title: ["Early-stage MENA SaaS founders", "مؤسسو SaaS في المنطقة بالمراحل المبكرة"], copy: ["Stages 1–3 founders who need proof, a repeatable route to buyers, and less runway spent on the wrong build.", "مؤسسو المراحل ١–٣ الذين يحتاجون إلى دليل ومسار متكرر للمشترين وإنفاق أقل للمدرج على البناء الخاطئ."], href: "/roadmap/validation", cta: ["Start with Validation", "ابدأ بالتحقق"] },
  { tag: ["02 / NEXT READINESS", "٠٢ / الجاهزية التالية"], title: ["Growth-stage founders and operators", "مؤسسون ومشغّلون في مرحلة النمو"], copy: ["Stages 4–7 teams managing retention, focus, expansion, and governance. Their curriculum paths open as the stages are completed.", "فرق المراحل ٤–٧ التي تدير الاحتفاظ والتركيز والتوسع والحوكمة. تفتح مساراتها التعليمية عند اكتمال المراحل."], href: "/roadmap/retention", cta: ["See the later-stage map", "شاهد خريطة المراحل اللاحقة"] },
  { tag: ["03 / PROVIDER", "٠٣ / مزود خدمة"], title: ["Specialists serving SaaS teams", "متخصصون يخدمون فرق SaaS"], copy: ["A curated, capped provider route for functions founders cannot yet afford to hire full time.", "مسار مزودين منتقى ومحدود للوظائف التي لا يستطيع المؤسسون توظيفها بدوام كامل بعد."], href: "/providers/join", cta: ["Apply as a provider", "تقدم كمزود خدمة"] },
  { tag: ["04 / PARTNER", "٠٤ / شريك"], title: ["Partners and sponsors", "شركاء ورعاة"], copy: ["Cloud, finance, VC, and ecosystem teams that want a clear asset, a relevant founder audience, and an accountable activation path.", "فرق السحابة والتمويل ورأس المال المغامر والمنظومة التي تريد أصلا واضحا وجمهورا من المؤسسين ومسار تفعيل قابل للمساءلة."], href: "/partners", cta: ["Build a partner brief", "أنشئ موجز شراكة"] },
] as const;

const revenueStreams = [
  ["01", "Subscriber access", "Annual platform access: the full video library and the SaaS AI Coach when it is ready.", "وصول المشترك", "وصول سنوي للمنصة: مكتبة الفيديو الكاملة ومرشد SaaS بالذكاء الاصطناعي عند جاهزيته."],
  ["02", "Stage cohorts", "A paid 3–4 week cohort for a specific roadmap stage, available after Subscriber access.", "دفعات المراحل", "دفعة مدفوعة من ٣–٤ أسابيع لمرحلة محددة من الخارطة، متاحة بعد وصول المشترك."],
  ["03", "Workshops", "Focused, paid working sessions for one consequential founder problem.", "ورش العمل", "جلسات عمل مدفوعة ومركزة لمشكلة مؤسس مهمة واحدة."],
  ["04", "Sponsorships", "Defined assets across the Summit, Demo Days, webinars, podcast, and future AI agent layer.", "الرعايات", "أصول محددة عبر القمة وأيام العرض والندوات والبودكاست وطبقة وكلاء الذكاء الاصطناعي المستقبلية."],
  ["05", "Provider listings", "A high-trust, capped directory route for vetted specialists serving MENA SaaS founders.", "إدراجات المزودين", "مسار دليل عالي الثقة ومحدود للمتخصصين الموثقين الذين يخدمون مؤسسي SaaS في المنطقة."],
] as const;

const phases = [
  { phase: ["PHASE 1 / PROVE", "المرحلة ١ / إثبات"], title: ["Teach what is ready", "علّم ما هو جاهز"], copy: ["Founder / CEO and Content & Curriculum own Stage 1–2 delivery, podcast credibility, and the first directory signal.", "يتولى المؤسس/الرئيس التنفيذي والمحتوى والمنهج تقديم المرحلتين ١–٢ ومصداقية البودكاست وإشارة الدليل الأولى."], roles: ["Founder / CEO", "Content & Curriculum"] },
  { phase: ["PHASE 2 / NETWORK", "المرحلة ٢ / الشبكة"], title: ["Build the trusted layer", "ابنِ طبقة الثقة"], copy: ["Community Management and Events create the directory, provider vetting, webinars, and useful recurring rooms.", "تبني إدارة المجتمع والفعاليات الدليل وتدقيق المزودين والندوات والغرف المتكررة المفيدة."], roles: ["Community Management", "Events", "Growth & Marketing"] },
  { phase: ["PHASE 3 / SCALE", "المرحلة ٣ / التوسع"], title: ["Compound the ecosystem", "ضاعف أثر المنظومة"], copy: ["AI & Product and Partnerships & Sponsorships formalize the Coach, tools, Summit, and sponsor programme once the underlying signal is real.", "تعمل منتجات وذكاء اصطناعي والشراكات والرعايات على إضفاء الطابع الرسمي على المرشد والأدوات والقمة وبرنامج الرعاة عندما تكون الإشارة الأساسية حقيقية."], roles: ["AI & Product", "Partnerships & Sponsorships", "Operations & Finance"] },
] as const;

export default function OperatingModel() {
  const { t, isRTL } = useLocale();
  const Arrow = isRTL ? ArrowLeft : ArrowRight;
  return <>
    <PageIntro
      label={t("Operating model", "نموذج التشغيل")}
      title={t("The operating system for SaaS founders in the Middle East.", "نظام التشغيل لمؤسسي SaaS في الشرق الأوسط.")}
      copy={t("ASaaSI combines stage-mapped education, a curated regional network, practical tools, and a connected AI guidance layer so a founder can build a recurring-revenue company without importing a playbook that was never built for this region.", "يجمع أساسي بين تعليم مرتبط بالمراحل وشبكة إقليمية منتقاة وأدوات عملية وطبقة إرشاد بالذكاء الاصطناعي متصلة، حتى يتمكن المؤسس من بناء شركة إيرادات متكررة دون استيراد دليل لم يُبن لهذه المنطقة.")}
      note={<div className="operating-model-route-map"><span className="mono">{t("OPERATING MAP / CURRENT SIGNAL", "خريطة التشغيل / الإشارة الحالية")}</span><div><i>01</i><strong>{t("Education", "التعليم")}</strong><small>{t("Stage 1–2 ready", "المرحلتان ١–٢ جاهزتان")}</small></div><div><i>02</i><strong>{t("Network", "الشبكة")}</strong><small>{t("Curated context", "سياق منتقى")}</small></div><div><i>03</i><strong>{t("Tools", "الأدوات")}</strong><small>{t("Decision support", "دعم القرار")}</small></div><p>{t("The remaining stages are mapped publicly and open as their curriculum is completed.", "المراحل المتبقية محددة علنا وتفتح عند اكتمال منهجها.")}</p></div>}
    />

    <section className="section operating-model-principles"><div className="container"><div className="section-header"><div><SectionLabel>{t("Mission / vision", "المهمة / الرؤية")}</SectionLabel><h2>{t("Foundational, regional, integrated, evidence-led, and compounding.", "تأسيسي وإقليمي ومتكامل وقائم على الدليل ومتراكم الأثر.")}</h2></div><p>{t("The product is not a course catalogue or a community feed. Education, Community, and Tools are one connected system; the SaaS AI Coach is the layer that makes their context useful together.", "المنتج ليس فهرس دورات أو موجز مجتمع. التعليم والمجتمع والأدوات نظام واحد متصل؛ ومرشد SaaS بالذكاء الاصطناعي هو الطبقة التي تجعل سياقها مفيدا معا.")}</p></div><div className="operating-model-principles__grid"><article><span>01</span><h3>{t("Mission", "المهمة")}</h3><p>{t("Give every MENA SaaS founder the structured education, curated network, and practical tools needed to build, run, and scale a sustainable recurring-revenue business.", "منح كل مؤسس SaaS في المنطقة التعليم المنظم والشبكة المنتقاة والأدوات العملية اللازمة لبناء وتشغيل وتوسيع عمل إيرادات متكررة مستدام.")}</p></article><article><span>02</span><h3>{t("Vision", "الرؤية")}</h3><p>{t("Become the first place a founder in the region turns to learn, connect, find tools, and get guided from the first paying customer through to exit.", "أن نصبح المكان الأول الذي يلجأ إليه مؤسس في المنطقة للتعلم والتواصل والعثور على الأدوات والحصول على الإرشاد من أول عميل دافع حتى التخارج.")}</p></article><article><span>03</span><h3>{t("Working rule", "قاعدة العمل")}</h3><p>{t("Every path must name the founder stage, the function at stake, and the evidence they should leave with, never generic startup motivation.", "يجب أن يسمي كل مسار مرحلة المؤسس والوظيفة المعنية والدليل الذي ينبغي أن يغادر به، لا تحفيزا عاما للشركات الناشئة.")}</p></article></div></div></section>

    <section className="section section-clay"><div className="container"><div className="section-header"><div><SectionLabel>{t("Who this is built for", "لمن بُني هذا")}</SectionLabel><h2>{t("One founder journey. Clear parallel paths for the people who make the ecosystem work.", "رحلة مؤسس واحدة. مسارات متوازية واضحة للأشخاص الذين يجعلون المنظومة تعمل.")}</h2></div><p>{t("Early-stage B2B and B2B2C SaaS founders are the primary audience today. Every other route exists to strengthen their ability to make a better next decision.", "مؤسسو SaaS من نوع B2B وB2B2C في المراحل المبكرة هم الجمهور الأساسي اليوم. كل مسار آخر موجود لتعزيز قدرتهم على اتخاذ القرار التالي بشكل أفضل.")}</p></div><div className="operating-audience-ledger">{audiences.map((audience) => <article key={audience.title[0]}><span className="mono">{t(audience.tag[0], audience.tag[1])}</span><div><h3>{t(audience.title[0], audience.title[1])}</h3><p>{t(audience.copy[0], audience.copy[1])}</p></div><Link href={audience.href} className="text-link">{t(audience.cta[0], audience.cta[1])} <Arrow size={14} /></Link></article>)}</div></div></section>

    <section className="section operating-strategy"><div className="container"><div className="section-header"><div><SectionLabel>{t("Why this system is different", "لماذا يختلف هذا النظام")}</SectionLabel><h2>{t("Region-specific context before generic scale.", "سياق خاص بالمنطقة قبل التوسع العام.")}</h2></div><p>{t("ASaaSI does not position itself as another generic founder community, course library, or freelancer marketplace. Its differentiation is the connection between the MENA SaaS stage, the practical function, the relevant person, and the next evidence-backed move.", "لا يقدّم أساسي نفسه كمجتمع مؤسسين عام آخر أو مكتبة دورات أو سوق مستقلين. يتمثل اختلافه في الربط بين مرحلة SaaS في المنطقة والوظيفة العملية والشخص ذي الصلة والخطوة التالية المدعومة بالدليل.")}</p></div><div className="operating-risk-ledger"><article><span>01</span><div><h3>{t("Trust before volume", "الثقة قبل الحجم")}</h3><p>{t("Providers are capped and vetted; introductions explain relevance; sponsored activity is tied to a clear founder outcome.", "المزودون محدودون ومدققون؛ تشرح المقدمات الملاءمة؛ ويرتبط النشاط المدعوم بنتيجة واضحة للمؤسس.")}</p></div></article><article><span>02</span><div><h3>{t("Readiness before promotion", "الجاهزية قبل الترويج")}</h3><p>{t("Only Validation and MVP ask a founder to enrol now. The remaining public frameworks are useful briefings, not premature course claims.", "فقط التحقق والمنتج الأولي يطلبان من المؤسس الالتحاق الآن. الأطر العامة المتبقية موجزات مفيدة، لا ادعاءات مبكرة عن دورات.")}</p></div></article><article><span>03</span><div><h3>{t("Evidence before forecast", "الدليل قبل التوقع")}</h3><p>{t("Revenue, pricing, and expansion assumptions remain planning inputs until real subscription, cohort, sponsorship, and provider data replaces them.", "تبقى افتراضات الإيرادات والتسعير والتوسع مدخلات تخطيط حتى تستبدلها بيانات حقيقية عن الاشتراكات والدفعات والرعايات والمزودين.")}</p></div></article></div></div></section>

    <section className="section"><div className="container"><div className="section-header"><div><SectionLabel>{t("One relationship, five revenue moments", "علاقة واحدة، خمس لحظات إيراد")}</SectionLabel><h2>{t("Monetise the value the founder has already experienced.", "حوّل القيمة التي اختبرها المؤسس بالفعل إلى إيراد.")}</h2></div><p>{t("The model is one deepening relationship: Visitor, Registered profile, Subscriber, then a paid stage cohort or workshop. Provider and sponsor programmes are parallel B2B tracks built on qualified founder demand.", "النموذج علاقة واحدة تتعمق: زائر، ملف مسجل، مشترك، ثم دفعة مرحلة مدفوعة أو ورشة عمل. برامج المزودين والرعاة مسارات B2B متوازية مبنية على طلب مؤسسين مؤهلين.")}</p></div><div className="operating-revenue-ledger">{revenueStreams.map((stream) => <article key={stream[1]}><span>{stream[0]}</span><div><h3>{t(stream[1], stream[3])}</h3><p>{t(stream[2], stream[4])}</p></div><Check size={16} /></article>)}</div></div></section>

    <section className="section section-dark operating-planning"><div className="container"><div className="section-header"><div><SectionLabel light>{t("Three-year planning view", "نظرة تخطيطية لثلاث سنوات")}</SectionLabel><h2>{t("A model to challenge with evidence, not a forecast to market.", "نموذج نختبره بالدليل، لا توقعا نسوق له.")}</h2></div><p>{t("The numbers below reproduce the supplied planning workbook’s calculated total-revenue outputs. They are explicitly illustrative inputs, not public targets, approved pricing, or financial guidance.", "تعيد الأرقام أدناه مخرجات إجمالي الإيرادات المحسوبة في ملف التخطيط المرفق. وهي مدخلات توضيحية صراحة وليست أهدافا عامة أو تسعيرا معتمدا أو إرشادا ماليا.")}</p></div><div className="operating-planning__table" role="table" aria-label={t("Illustrative three-year revenue model", "نموذج إيرادات توضيحي لثلاث سنوات")}><div role="row"><span>{t("Planning horizon", "أفق التخطيط")}</span><strong>{t("Year 1", "السنة ١")}</strong><strong>{t("Year 2", "السنة ٢")}</strong><strong>{t("Year 3", "السنة ٣")}</strong></div><div role="row"><span>{t("Illustrative total revenue", "إجمالي الإيرادات التوضيحي")}</span><strong>$95,460</strong><strong>$323,800</strong><strong>$998,000</strong></div><div role="row"><span>{t("Curriculum readiness", "جاهزية المنهج")}</span><p>{t("2 sellable stages", "مرحلتان قابلتان للبيع")}</p><p>{t("4 planned stages", "٤ مراحل مخططة")}</p><p>{t("7 planned stages", "٧ مراحل مخططة")}</p></div></div><p className="operating-planning__note">{t("Source basis: the user-supplied August 2026 Revenue & Financial Projections workbook. Inputs must be replaced with real subscription, cohort, workshop, sponsorship, and provider-listing data as it becomes available.", "أساس المصدر: ملف الإيرادات والتوقعات المالية لشهر أغسطس ٢٠٢٦ الذي قدمه المستخدم. يجب استبدال المدخلات ببيانات حقيقية عن الاشتراكات والدفعات وورش العمل والرعايات وإدراجات المزودين عند توفرها.")}</p></div></section>

    <section className="section"><div className="container"><div className="section-header"><div><SectionLabel>{t("Organisation and roles", "المنظمة والأدوار")}</SectionLabel><h2>{t("Name the function before you hire the title.", "سمِّ الوظيفة قبل أن توظف المسمى.")}</h2></div><p>{t("This is a functional operating map, not a headcount promise. Ownership evolves as the company moves from proving the model to compounding the ecosystem.", "هذه خريطة تشغيلية وظيفية وليست وعدا بعدد الموظفين. تتطور الملكية مع انتقال الشركة من إثبات النموذج إلى مضاعفة أثر المنظومة.")}</p></div><div className="operating-role-phases">{phases.map((phase) => <article key={phase.phase[0]}><span className="mono">{t(phase.phase[0], phase.phase[1])}</span><h3>{t(phase.title[0], phase.title[1])}</h3><p>{t(phase.copy[0], phase.copy[1])}</p><div>{phase.roles.map((role) => <span key={role}>{role}</span>)}</div></article>)}</div></div></section>

    <section className="section"><div className="container"><div className="operating-model-cta"><div><SectionLabel>{t("Bring this into your company", "طبّق هذا في شركتك")}</SectionLabel><h2>{t("Now build the same clarity into your own company.", "الآن ابنِ الوضوح نفسه داخل شركتك.")}</h2><p>{t("The phases above are ASaaSI's own operating map. Create a company workspace to give your team the same named roles and accountable requests.", "المراحل أعلاه هي خريطة التشغيل الخاصة بأساسي. أنشئ مساحة عمل لشركتك لتمنح فريقك الأدوار المسماة نفسها والطلبات المسؤولة.")}</p></div><div><Link href="/organizations/new" className="button button-primary">{t("Create company workspace", "أنشئ مساحة عمل للشركة")} <Arrow size={15} /></Link><Link href="/organizations/join" className="button button-ghost">{t("Join a company workspace", "انضم لمساحة عمل شركة")} <Arrow size={15} /></Link></div></div></div></section>
  </>;
}
