/* Strategy-aligned membership path: Visitor → Registered → Subscriber, with course access gated truthfully and no unvalidated public prices. */
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { Link, useLocation } from "wouter";
import { PageIntro, SectionLabel, SignalTag } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";

const accessStates = [
  { name: "Visitor", nameAr: "زائر", state: "No account", stateAr: "بلا حساب", copy: "Browse public articles, selected learning, event listings, and the ecosystem before you share any context.", copyAr: "تصفح المقالات العامة والتعلم المختار وقوائم الفعاليات والمنظومة قبل أن تشارك أي سياق.", features: ["Public learning and event discovery", "See the seven-stage roadmap", "Decide whether the system fits your company"], featuresAr: ["تعلم عام واكتشاف الفعاليات", "شاهد خارطة النمو ذات السبع مراحل", "قرر إن كان النظام يناسب شركتك"], href: "/learn", cta: "Explore the system", ctaAr: "استكشف النظام" },
  { name: "Registered", nameAr: "مسجل", state: "Free profile", stateAr: "ملف مجاني", copy: "Create a useful founder, operator, provider, or partner profile and contribute to the directory’s regional signal.", copyAr: "أنشئ ملفا مفيدا لمؤسس أو مشغل أو مزود أو شريك وساهم في الإشارة الإقليمية للدليل.", features: ["Directory visibility and limited content", "Stage-aware people and event recommendations", "A free profile before any payment decision"], featuresAr: ["ظهور في الدليل ومحتوى محدود", "توصيات أشخاص وفعاليات واعية بالمرحلة", "ملف مجاني قبل أي قرار دفع"], href: "/signup", cta: "Create free profile", ctaAr: "أنشئ ملفا مجانيا", highlight: true },
  { name: "Subscriber", nameAr: "مشترك", state: "Annual platform access", stateAr: "وصول سنوي للمنصة", copy: "Unlock the full video library and the SaaS AI Coach when it is ready. An active Subscriber account is required before any paid course enrolment.", copyAr: "افتح مكتبة الفيديو الكاملة ومرشد SaaS بالذكاء الاصطناعي عند جاهزيته. يتطلب الالتحاق بأي دورة مدفوعة حساب مشترك نشطا.", features: ["Full platform learning access", "Required gate before paid Stage 1–2 cohorts", "Subscriber-to-course path, not a bundled course promise"], featuresAr: ["وصول كامل لتعلم المنصة", "شرط قبل دفعات المرحلتين ١–٢ المدفوعة", "مسار من مشترك إلى دورة، لا وعد دورة مجمعة"], href: "/signup", cta: "Create profile — subscription opens after", ctaAr: "أنشئ ملفا — الاشتراك يُفتح لاحقا" },
];

export default function Pricing() {
  const { t, formatNum, isRTL } = useLocale();
  const [location] = useLocation();
  const isPricingView = location.startsWith("/pricing");
  const Arrow = isRTL ? ArrowLeft : ArrowRight;
  const decisionSteps = isPricingView ? [
    { trigger: t("I need to name the buyer whose constraint is worth solving.", "أحتاج لتسمية المشتري الذي يستحق قيده الحل."), unlock: t("Define the accountable buyer, their moment of need, and the alternative they use today.", "حدد المشتري المسؤول ولحظة حاجته والبديل الذي يستخدمه اليوم."), plan: t("Buyer / constraint", "المشتري / القيد") },
    { trigger: t("I need evidence that the promise creates a useful outcome.", "أحتاج دليلا أن الوعد يصنع نتيجة مفيدة."), unlock: t("Connect the outcome, proof point, and delivery boundary before choosing a package.", "اربط النتيجة ونقطة الدليل وحد التسليم قبل اختيار الباقة."), plan: t("Value / proof", "القيمة / الدليل") },
    { trigger: t("I need a price I can explain without hiding the trade-off.", "أحتاج سعرا يمكنني شرحه من دون إخفاء المقايضة."), unlock: t("Turn the buyer and proof into a scoped price hypothesis, then test it with the right demand.", "حوّل المشتري والدليل إلى فرضية سعر محددة ثم اختبرها مع الطلب المناسب."), plan: t("Price / test", "السعر / الاختبار") },
  ] : [
    { trigger: t("I need to see whether this is regionally and stage-specific.", "أحتاج لمعرفة هل هذا إقليمي ومحدد بالمرحلة."), unlock: t("Browse public signals and the roadmap.", "تصفح الإشارات العامة والخارطة."), plan: t("Visitor / discovery", "زائر / اكتشاف") },
    { trigger: t("I need the network to understand my company context.", "أحتاج أن تفهم الشبكة سياق شركتي."), unlock: t("Create a free profile and join the directory signal.", "أنشئ ملفا مجانيا وانضم إلى إشارة الدليل."), plan: t("Registered / profile", "مسجل / ملف") },
    { trigger: t("I need the full learning and guidance layer.", "أحتاج طبقة التعلم والإرشاد الكاملة."), unlock: t("Move to annual Subscriber access before a paid Stage 1–2 cohort.", "انتقل إلى وصول مشترك سنوي قبل دفعة مدفوعة للمرحلتين ١–٢."), plan: t("Subscriber / platform", "مشترك / منصة") },
  ];
  return <>
    <PageIntro label={isPricingView ? t("Pricing / Decision map", "التسعير / خريطة القرار") : t("Membership / Access path", "العضوية / مسار الوصول")} title={isPricingView ? t("Price the promise only after the buyer and value are legible.", "سعّر الوعد فقط بعد أن يصبح المشتري والقيمة واضحين.") : t("Start with context. Subscribe when the full system removes a real constraint.", "ابدأ بالسياق. اشترك عندما يزيل النظام الكامل قيدا حقيقيا.")} copy={isPricingView ? t("ASaaSI does not publish unvalidated numbers. Use the buyer, the proof of value, and the delivery boundary to form a price hypothesis worth testing.", "لا ينشر أساسي أرقاما غير مثبتة. استخدم المشتري ودليل القيمة وحد التسليم لتكوين فرضية سعر تستحق الاختبار.") : t("ASaaSI is built around one relationship that deepens over time: public discovery, a free profile, annual Subscriber access, then a paid roadmap course or workshop when it matches the stage you are actually in.", "بُني أساسي حول علاقة واحدة تتعمق بمرور الوقت: اكتشاف عام، وملف مجاني، ووصول مشترك سنوي، ثم دورة خارطة نمو أو ورشة مدفوعة عندما تناسب المرحلة التي أنت فيها فعلا.")} note={<div className="hero-aside-note"><span className="mono">{isPricingView ? t("PRICE DISCIPLINE", "انضباط التسعير") : t("ACCESS RULE", "قاعدة الوصول")}</span><strong>{isPricingView ? t("A number follows a defined promise; it never substitutes for one.", "يأتي الرقم بعد وعد محدد؛ ولا يحل محله أبدا.") : t("Subscriber access comes before a paid cohort course.", "وصول المشترك يسبق أي دفعة دورة مدفوعة.")}</strong><p>{isPricingView ? t("Courses, workshops, sponsors, and provider terms are scoped to real demand rather than placed in a generic price table.", "تُحدد شروط الدورات وورش العمل والرعاة والمزودين وفقا للطلب الحقيقي بدلا من وضعها في جدول أسعار عام.") : t("Stage 1 and Stage 2 are ready today. Stages 3–7 remain mapped as their curricula are developed.", "المرحلتان ١ و٢ جاهزتان اليوم. تبقى المراحل ٣–٧ محددة أثناء تطوير مناهجها.")}</p><Link href={isPricingView ? "/tools/pricing" : "/roadmap/validation"} className="button button-primary button-small">{isPricingView ? t("Open pricing tool", "افتح أداة التسعير") : t("See the roadmap", "شاهد الخارطة")} <Arrow size={14} /></Link></div>} />
    <section className="section pricing-decision-section"><div className="container"><div className="section-header pricing-decision-heading"><div><SectionLabel>{isPricingView ? t("The pricing decision path", "مسار قرار التسعير") : t("The founder access sequence", "تسلسل وصول المؤسس")}</SectionLabel><h2>{isPricingView ? t("Make the buyer, value, and trade-off visible before the number.", "اجعل المشتري والقيمة والمقايضة واضحة قبل الرقم.") : t("Use the system in the order that proves its value.", "استخدم النظام بالترتيب الذي يثبت قيمته.")}</h2></div><p>{isPricingView ? t("A useful price makes one promise legible to one buyer with a delivery boundary the company can actually hold.", "السعر المفيد يجعل وعدا واحدا واضحا لمشتر واحد بحد تسليم تستطيع الشركة الالتزام به فعلا.") : t("No one needs to pay to find out whether ASaaSI understands their stage. Subscriber access becomes relevant once the full library and connected guidance can move the work in front of them.", "لا يحتاج أحد للدفع كي يعرف هل يفهم أساسي مرحلته. يصبح وصول المشترك ذا صلة عندما تستطيع المكتبة الكاملة والإرشاد المتصل تحريك العمل الذي أمامه.")}</p></div><ol className="pricing-decision-map">
      {/* ponytail: was `index === 1 ? "is-current"` - a fixed array position styled as "you are
          here" regardless of the visitor's real account state (Visitor/Registered/Subscriber),
          so it claimed the same false position for every viewer. This is an explanatory
          sequence, not a personalized status, so no step is marked current until real
          auth-state-driven step tracking exists. */}
      {decisionSteps.map((step, index) => <li key={step.plan}><span className="pricing-decision-node">{formatNum(index + 1)}</span><div><span className="mono">{isPricingView ? t("DECISION", "القرار") : t("THE MOMENT", "اللحظة")}</span><h3>{step.trigger}</h3></div><div><span className="mono">{isPricingView ? t("WHAT BECOMES LEGIBLE", "ما يصبح واضحا") : t("WHAT OPENS", "ما الذي ينفتح")}</span><p>{step.unlock}</p></div><strong>{step.plan}</strong></li>)}</ol></div></section>
    <section className="section"><div className="container">{isPricingView ? <div className="pricing-value-ledger"><div className="pricing-value-ledger__head"><SectionLabel>{t("Price hypothesis record", "سجل فرضية السعر")}</SectionLabel><p>{t("A price is reviewed against a buyer, a value proof, and a delivery boundary, not presented as a broad public promise.", "يُراجع السعر مقابل المشتري ودليل القيمة وحد التسليم، ولا يقدم كوعد عام واسع.")}</p></div>{decisionSteps.map((step, index) => <article key={step.plan}><span>{formatNum(index + 1)}</span><div><small>{step.plan}</small><h3>{step.trigger}</h3></div><p>{step.unlock}</p><Link href="/tools/pricing" className="text-link">{index === 0 ? t("Define buyer", "حدد المشتري") : index === 1 ? t("Record proof", "سجل الدليل") : t("Test hypothesis", "اختبر الفرضية")} <Arrow size={14} /></Link></article>)}</div> : <div className="pricing-grid">{accessStates.map((state) => <article key={state.name} className={`plan ${state.highlight ? "highlight" : ""}`}>{state.highlight && <SignalTag>{t("The useful first commitment", "الالتزام الأول المفيد")}</SignalTag>}<span className="mono">{t(state.state, state.stateAr)}</span><h3>{t(state.name, state.nameAr)}</h3><p>{t(state.copy, state.copyAr)}</p><div className="plan-features">{state.features.map((feature, index) => <div key={feature}><Check className="check" size={15} />{t(feature, state.featuresAr[index])}</div>)}</div><Link href={state.href} className={`button ${state.highlight ? "button-primary" : "button-ghost"}`}>{t(state.cta, state.ctaAr)} <Arrow size={14} /></Link></article>)}</div>}</div></section>
    <section className="section section-dark"><div className="container"><div className="section-header"><div><SectionLabel light>{t("What the model protects", "ما الذي يحميه النموذج")}</SectionLabel><h2>{t("Evidence before payment. Context before a course. A real stage before a promise.", "دليل قبل الدفع. سياق قبل الدورة. مرحلة حقيقية قبل الوعد.")}</h2></div><p>{t("Course pricing, workshop pricing, sponsor packages, and provider-listing terms are scoped against real demand rather than advertised as unvalidated public numbers.", "يُحدد تسعير الدورات وورش العمل وحزم الرعاة وشروط إدراج المزودين وفقا للطلب الحقيقي بدلا من الإعلان عنها كأرقام عامة غير مثبتة.")}</p></div><div className="proof-strip"><div className="proof-cell accent"><strong>{formatNum(1)}</strong><span>{t("A free profile proves whether the network context is useful.", "يثبت الملف المجاني ما إذا كان سياق الشبكة مفيدا.")}</span></div><div className="proof-cell"><strong>{formatNum(2)}</strong><span>{t("Subscriber access is platform value, not a disguised course bundle.", "وصول المشترك قيمة للمنصة، لا حزمة دورات مقنّعة.")}</span></div><div className="proof-cell"><strong>{formatNum(3)}</strong><span>{t("Only the ready Stage 1–2 curriculum can ask a founder to enrol now.", "فقط منهج المرحلتين ١–٢ الجاهز يمكن أن يطلب من المؤسس الالتحاق الآن.")}</span></div><div className="proof-cell"><strong>{formatNum(4)}</strong><span>{t("Provider and sponsor routes are parallel B2B relationships, not founder upsells.", "مسارات المزودين والرعاة علاقات B2B متوازية، لا ترقيات للمؤسسين.")}</span></div></div></div></section>
    <section className="section"><div className="container form-shell"><div><SectionLabel>{t("Need the whole map?", "تحتاج الخريطة كاملة؟")}</SectionLabel><h2>{t("See the roles, stages, and revenue logic behind the public experience.", "شاهد الأدوار والمراحل ومنطق الإيرادات خلف التجربة العامة.")}</h2><p>{t("The operating model explains who ASaaSI is for, what is ready now, how the organisation sequences work, and how the five revenue streams fit one ecosystem.", "يوضح نموذج التشغيل لمن بُني أساسي وما هو جاهز الآن وكيف تنظم المنظمة العمل وكيف تتكامل تدفقات الإيرادات الخمسة في منظومة واحدة.")}</p></div><div className="resource-card"><SignalTag tone="soft">{t("Strategic foundation", "أساس استراتيجي")}</SignalTag><h3>{t("Read the operating model.", "اقرأ نموذج التشغيل.")}</h3><p>{t("Clear promise, clear audiences, clear delivery sequence.", "وعد واضح وجماهير واضحة وتسلسل تقديم واضح.")}</p><Link href="/operating-model" className="button button-dark">{t("Open operating model", "افتح نموذج التشغيل")} <Arrow size={15} /></Link></div></div></section>
  </>;
}
