/* Strategy-aligned membership path: Visitor → Registered → Subscriber, with course access gated truthfully and no unvalidated public prices. */
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { Link } from "wouter";
import { PageIntro, SectionLabel, SignalTag } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";

const accessStates = [
  { name: "Visitor", nameAr: "زائر", state: "No account", stateAr: "بلا حساب", copy: "Browse public articles, selected learning, event listings, and the ecosystem before you share any context.", copyAr: "تصفح المقالات العامة والتعلم المختار وقوائم الفعاليات والمنظومة قبل أن تشارك أي سياق.", features: ["Public learning and event discovery", "See the seven-stage roadmap", "Decide whether the system fits your company"], featuresAr: ["تعلم عام واكتشاف الفعاليات", "شاهد خارطة النمو ذات السبع مراحل", "قرر إن كان النظام يناسب شركتك"], href: "/learn", cta: "Explore the system", ctaAr: "استكشف النظام" },
  { name: "Registered", nameAr: "مسجل", state: "Free profile", stateAr: "ملف مجاني", copy: "Create a useful founder, operator, provider, or partner profile and contribute to the directory’s regional signal.", copyAr: "أنشئ ملفا مفيدا لمؤسس أو مشغل أو مزود أو شريك وساهم في الإشارة الإقليمية للدليل.", features: ["Directory visibility and limited content", "Stage-aware people and event recommendations", "A free profile before any payment decision"], featuresAr: ["ظهور في الدليل ومحتوى محدود", "توصيات أشخاص وفعاليات واعية بالمرحلة", "ملف مجاني قبل أي قرار دفع"], href: "/signup", cta: "Create free profile", ctaAr: "أنشئ ملفا مجانيا", highlight: true },
  { name: "Subscriber", nameAr: "مشترك", state: "Annual platform access", stateAr: "وصول سنوي للمنصة", copy: "Unlock the full video library and the SaaS AI Coach when it is ready. An active Subscriber account is required before any paid course enrolment.", copyAr: "افتح مكتبة الفيديو الكاملة ومرشد SaaS بالذكاء الاصطناعي عند جاهزيته. يتطلب الالتحاق بأي دورة مدفوعة حساب مشترك نشطا.", features: ["Full platform learning access", "Required gate before paid Stage 1–2 cohorts", "Subscriber-to-course path, not a bundled course promise"], featuresAr: ["وصول كامل لتعلم المنصة", "شرط قبل دفعات المرحلتين ١–٢ المدفوعة", "مسار من مشترك إلى دورة، لا وعد دورة مجمعة"], href: "/signup", cta: "Start with your profile", ctaAr: "ابدأ بملفك" },
];

export default function Pricing() {
  const { t, formatNum, isRTL } = useLocale();
  const Arrow = isRTL ? ArrowLeft : ArrowRight;
  return <>
    <PageIntro label={t("Membership / Access path", "العضوية / مسار الوصول")} title={t("Start with context. Subscribe when the full system removes a real constraint.", "ابدأ بالسياق. اشترك عندما يزيل النظام الكامل قيدا حقيقيا.")} copy={t("ASaaSI is built around one relationship that deepens over time: public discovery, a free profile, annual Subscriber access, then a paid roadmap course or workshop when it matches the stage you are actually in.", "بُني أساسي حول علاقة واحدة تتعمق بمرور الوقت: اكتشاف عام، وملف مجاني، ووصول مشترك سنوي، ثم دورة خارطة نمو أو ورشة مدفوعة عندما تناسب المرحلة التي أنت فيها فعلا.")} note={<div className="hero-aside-note"><span className="mono">{t("ACCESS RULE", "قاعدة الوصول")}</span><strong>{t("Subscriber access comes before a paid cohort course.", "وصول المشترك يسبق أي دفعة دورة مدفوعة.")}</strong><p>{t("Stage 1 and Stage 2 are ready today. Stages 3–7 remain mapped as their curricula are developed.", "المرحلتان ١ و٢ جاهزتان اليوم. تبقى المراحل ٣–٧ محددة أثناء تطوير مناهجها.")}</p><Link href="/roadmap/validation" className="button button-primary button-small">{t("See the roadmap", "شاهد الخارطة")} <Arrow size={14} /></Link></div>} />
    <section className="section pricing-decision-section"><div className="container"><div className="section-header pricing-decision-heading"><div><SectionLabel>{t("The founder access sequence", "تسلسل وصول المؤسس")}</SectionLabel><h2>{t("Use the system in the order that proves its value.", "استخدم النظام بالترتيب الذي يثبت قيمته.")}</h2></div><p>{t("No one needs to pay to find out whether ASaaSI understands their stage. Subscriber access becomes relevant once the full library and connected guidance can move the work in front of them.", "لا يحتاج أحد للدفع كي يعرف هل يفهم أساسي مرحلته. يصبح وصول المشترك ذا صلة عندما تستطيع المكتبة الكاملة والإرشاد المتصل تحريك العمل الذي أمامه.")}</p></div><ol className="pricing-decision-map">{[
      { trigger: t("I need to see whether this is regionally and stage-specific.", "أحتاج لمعرفة هل هذا إقليمي ومحدد بالمرحلة."), unlock: t("Browse public signals and the roadmap.", "تصفح الإشارات العامة والخارطة."), plan: t("Visitor / discovery", "زائر / اكتشاف") },
      { trigger: t("I need the network to understand my company context.", "أحتاج أن تفهم الشبكة سياق شركتي."), unlock: t("Create a free profile and join the directory signal.", "أنشئ ملفا مجانيا وانضم إلى إشارة الدليل."), plan: t("Registered / profile", "مسجل / ملف") },
      { trigger: t("I need the full learning and guidance layer.", "أحتاج طبقة التعلم والإرشاد الكاملة."), unlock: t("Move to annual Subscriber access before a paid Stage 1–2 cohort.", "انتقل إلى وصول مشترك سنوي قبل دفعة مدفوعة للمرحلتين ١–٢."), plan: t("Subscriber / platform", "مشترك / منصة") },
    ].map((step, index) => <li key={step.plan} className={index === 1 ? "is-current" : ""}><span className="pricing-decision-node">{formatNum(index + 1)}</span><div><span className="mono">{t("THE MOMENT", "اللحظة")}</span><h3>{step.trigger}</h3></div><div><span className="mono">{t("WHAT OPENS", "ما الذي ينفتح")}</span><p>{step.unlock}</p></div><strong>{step.plan}</strong></li>)}</ol></div></section>
    <section className="section"><div className="container"><div className="pricing-grid">{accessStates.map((state) => <article key={state.name} className={`plan ${state.highlight ? "highlight" : ""}`}>{state.highlight && <SignalTag>{t("The useful first commitment", "الالتزام الأول المفيد")}</SignalTag>}<span className="mono">{t(state.state, state.stateAr)}</span><h3>{t(state.name, state.nameAr)}</h3><p>{t(state.copy, state.copyAr)}</p><div className="plan-price">{t(state.state, state.stateAr)}</div><div className="plan-features">{state.features.map((feature, index) => <div key={feature}><Check className="check" size={15} />{t(feature, state.featuresAr[index])}</div>)}</div><Link href={state.href} className={`button ${state.highlight ? "button-primary" : "button-ghost"}`}>{t(state.cta, state.ctaAr)} <Arrow size={14} /></Link></article>)}</div></div></section>
    <section className="section section-dark"><div className="container"><div className="section-header"><div><SectionLabel light>{t("What the model protects", "ما الذي يحميه النموذج")}</SectionLabel><h2>{t("Evidence before payment. Context before a course. A real stage before a promise.", "دليل قبل الدفع. سياق قبل الدورة. مرحلة حقيقية قبل الوعد.")}</h2></div><p>{t("Course pricing, workshop pricing, sponsor packages, and provider-listing terms are scoped against real demand rather than advertised as unvalidated public numbers.", "يُحدد تسعير الدورات وورش العمل وحزم الرعاة وشروط إدراج المزودين وفقا للطلب الحقيقي بدلا من الإعلان عنها كأرقام عامة غير مثبتة.")}</p></div><div className="proof-strip"><div className="proof-cell accent"><strong>{formatNum(1)}</strong><span>{t("A free profile proves whether the network context is useful.", "يثبت الملف المجاني ما إذا كان سياق الشبكة مفيدا.")}</span></div><div className="proof-cell"><strong>{formatNum(2)}</strong><span>{t("Subscriber access is platform value, not a disguised course bundle.", "وصول المشترك قيمة للمنصة، لا حزمة دورات مقنّعة.")}</span></div><div className="proof-cell"><strong>{formatNum(3)}</strong><span>{t("Only the ready Stage 1–2 curriculum can ask a founder to enrol now.", "فقط منهج المرحلتين ١–٢ الجاهز يمكن أن يطلب من المؤسس الالتحاق الآن.")}</span></div><div className="proof-cell"><strong>{formatNum(4)}</strong><span>{t("Provider and sponsor routes are parallel B2B relationships, not founder upsells.", "مسارات المزودين والرعاة علاقات B2B متوازية، لا ترقيات للمؤسسين.")}</span></div></div></div></section>
    <section className="section"><div className="container form-shell"><div><SectionLabel>{t("Need the whole map?", "تحتاج الخريطة كاملة؟")}</SectionLabel><h2>{t("See the roles, stages, and revenue logic behind the public experience.", "شاهد الأدوار والمراحل ومنطق الإيرادات خلف التجربة العامة.")}</h2><p>{t("The operating model explains who ASaaSI is for, what is ready now, how the organisation sequences work, and how the five revenue streams fit one ecosystem.", "يوضح نموذج التشغيل لمن بُني أساسي وما هو جاهز الآن وكيف تنظم المنظمة العمل وكيف تتكامل تدفقات الإيرادات الخمسة في منظومة واحدة.")}</p></div><div className="resource-card"><SignalTag tone="soft">{t("Strategic foundation", "أساس استراتيجي")}</SignalTag><h3>{t("Read the operating model.", "اقرأ نموذج التشغيل.")}</h3><p>{t("Clear promise, clear audiences, clear delivery sequence.", "وعد واضح وجماهير واضحة وتسلسل تقديم واضح.")}</p><Link href="/operating-model" className="button button-dark">{t("Open operating model", "افتح نموذج التشغيل")} <Arrow size={15} /></Link></div></div></section>
  </>;
}
