/* Editorial Operating System, bilingual self-service help with clear categories and recovery paths. */
import { useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, MessageCircle, ShieldQuestion } from "lucide-react";
import { Link } from "wouter";
import { PageIntro, SectionLabel, SignalTag } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";

const guides = [
  { tone: "soft", icon: BookOpen, label: ["Guides", "أدلة"], title: ["Start with the basics.", "ابدأ بالأساسيات."], copy: ["Account, membership, profile, privacy, and getting your first useful recommendation.", "الحساب والعضوية والملف والخصوصية والحصول على أول توصية مفيدة."], link: ["/learn", "Browse guides", "تصفح الأدلة"] },
  { tone: "clay", icon: MessageCircle, label: ["Community", "المجتمع"], title: ["Questions about the community?", "لديك أسئلة عن المجتمع؟"], copy: ["Understand requests, introductions, groups, moderation, and how to participate with care.", "افهم الطلبات والمقدمات والمجموعات والإشراف وكيف تشارك بعناية."], link: ["/community", "Community help", "مساعدة المجتمع"] },
  { tone: "", icon: ShieldQuestion, label: ["Trust", "ثقة"], title: ["Know what is shared.", "اعرف ما تتم مشاركته."], copy: ["Privacy choices, visibility, verification standards, and how ASaaSI handles reports.", "خيارات الخصوصية والظهور ومعايير التحقق وكيف يتعامل أساسي مع البلاغات."], link: ["/privacy", "Read trust notes", "اقرأ ملاحظات الثقة"] },
] as const;

const faqs = [
  { q: "How does a focused introduction work?", a: "You share why the introduction would be useful and what you are working on. The other person can accept, decline, or suggest a different next step. Contact details are only shared after both sides agree.", arQ: "كيف تعمل المقدمة المركزة؟", arA: "تشارك سبب فائدة المقدمة وما تعمل عليه. يمكن للطرف الآخر القبول أو الرفض أو اقتراح خطوة مختلفة. لا تتم مشاركة بيانات الاتصال إلا بعد موافقة الطرفين." },
  { q: "Can I attend events without joining?", a: "Some events are open to the wider founder community and some are member-only. Each event page should show the access model, price, capacity, and what to expect before you register.", arQ: "هل يمكنني حضور الفعاليات دون الانضمام؟", arA: "بعض الفعاليات مفتوحة لمجتمع المؤسسين الأوسع وبعضها للأعضاء فقط. يجب أن تعرض كل صفحة فعالية نموذج الوصول والسعر والسعة وما تتوقعه قبل التسجيل." },
  { q: "What happens to my founder brief?", a: "Your brief is used to personalize recommendations. You choose what is public on your profile, and you can update or remove the information you provide.", arQ: "ماذا يحدث لموجز المؤسس الخاص بي؟", arA: "يُستخدم موجزك لتخصيص التوصيات. أنت تختار ما هو عام في ملفك، ويمكنك تحديث المعلومات التي تقدمها أو حذفها." },
  { q: "How do the founder tools work?", a: "Each tool explains its purpose, the time and inputs it needs, its assumptions, and what it cannot know. Tool outputs are prompts for better decisions, not a replacement for professional advice.", arQ: "كيف تعمل أدوات المؤسس؟", arA: "تشرح كل أداة هدفها والوقت والمدخلات التي تحتاجها وافتراضاتها وما لا يمكنها معرفته. نتائج الأدوات محفزات لقرارات أفضل وليست بديلا عن المشورة المهنية." },
];

export default function Support() {
  const { t, isRTL } = useLocale();
  const [open, setOpen] = useState(0);
  return <><PageIntro label={t("Support / Help center", "الدعم / مركز المساعدة")} title={t("Find the answer, keep the momentum.", "اعثر على الإجابة، وحافظ على الزخم.")} copy={t("Clear help for accounts, events, introductions, tools, and membership. If the answer is not here, we’ll route your question to the right person.", "مساعدة واضحة للحسابات والفعاليات والمقدمات والأدوات والعضوية. إذا لم تجد الإجابة هنا، سنوجه سؤالك إلى الشخص المناسب.")} note={<div className="hero-aside-note"><SignalTag tone="clay">{t("Need a human?", "تحتاج شخصا؟")}</SignalTag><p>{t("Tell us what happened and what you were trying to do. Context helps us help quickly.", "أخبرنا بما حدث وما كنت تحاول فعله. السياق يساعدنا على مساعدتك بسرعة.")}</p><Link href="/contact" className="button button-primary button-small">{t("Contact support", "تواصل مع الدعم")} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</Link></div>} /><section className="section"><div className="container"><div className="support-grid support-grid--lead">{guides.map((guide, index) => { const Icon = guide.icon; return <article className={`support-card ${index === 0 ? "support-card--lead" : ""}`} key={guide.label[0]}><SignalTag tone={guide.tone}><Icon size={13} /> {t(guide.label[0], guide.label[1])}</SignalTag><h3>{t(guide.title[0], guide.title[1])}</h3><p>{t(guide.copy[0], guide.copy[1])}</p><Link href={guide.link[0]} className="section-link">{t(guide.link[1], guide.link[2])} <span>→</span></Link></article>; })}</div></div></section><section className="section section-clay"><div className="container support-faq-layout"><div className="support-faq-layout__intro"><SectionLabel>{t("Common questions", "أسئلة شائعة")}</SectionLabel><h2 className="ds-display-m">{t("The details that help you decide.", "التفاصيل التي تساعدك على القرار.")}</h2><p className="ds-lede">{t("Still stuck? Give us the short version of the issue and we’ll take it from there.", "ما زلت عالقا؟ أعطنا النسخة المختصرة من المشكلة وسنتولى الباقي.")}</p></div><div className="faq-list">{faqs.map((faq, index) => <div className="faq-row" key={faq.q}><button id={`support-faq-trigger-${index}`} onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index} aria-controls={`support-faq-panel-${index}`}>{t(faq.q, faq.arQ)}<span>{open === index ? "−" : "+"}</span></button>{open === index && <p id={`support-faq-panel-${index}`} role="region" aria-labelledby={`support-faq-trigger-${index}`}>{t(faq.a, faq.arA)}</p>}</div>)}</div></div></section><section className="section"><div className="container"><div className="cta-band" style={{ padding: 48 }}><SectionLabel>{t("Not finding it", "لم تجده؟")}</SectionLabel><h2>{t("Tell us where the page lost you.", "أخبرنا أين فقدتك الصفحة.")}</h2><Link href="/contact" className="button button-dark">{t("Send a question", "أرسل سؤالا")} {isRTL ? <ArrowLeft size={15} /> : <ArrowRight size={15} />}</Link></div></div></section></>;
}
