/* Editorial Operating System, bilingual tools are an editorial workbench: lead decision, visible assumptions, and a concrete next move. */
/* Editorial operating system: Tools is a workbench—transparent inputs, visible assumptions, and a concrete next action. */
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Calculator, CheckSquare2, CircleGauge, LineChart, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { ToolCard, PageIntro, SectionLabel, SignalTag, Toast, useToast } from "../components/site";
import { useLocale } from "../contexts/LocaleContext";

const toolStages = ["All decisions", "Baseline", "Scenario", "Strategy", "Finance", "People", "Growth", "Readiness"] as const;
const stageArabic: Record<(typeof toolStages)[number], string> = { "All decisions": "كل القرارات", Baseline: "الأساس", Scenario: "السيناريو", Strategy: "الاستراتيجية", Finance: "التمويل", People: "الأشخاص", Growth: "النمو", Readiness: "الجاهزية" };
const tools = [
  { stage: "Baseline", tag: "Know your baseline", title: "Founder diagnostic", copy: "See the four dimensions shaping your next season of work.", duration: "3 min · private", tone: "soft", href: "/tools/founder-diagnostic", next: "Frame the question", arTag: "اعرف خط أساسك", arTitle: "تشخيص المؤسس", arCopy: "شاهد الأبعاد الأربعة التي تشكل موسم عملك التالي.", arDuration: "٣ دقائق · خاص", arNext: "صغ السؤال" },
  { stage: "Scenario", tag: "Run the scenario", title: "Survival calculator", copy: "Model runway with clear assumptions, currencies, and the next lever to inspect.", duration: "5 min · exportable", tone: "clay", href: "/tools/survival-calculator", next: "Test the inputs", arTag: "شغل السيناريو", arTitle: "حاسبة الاستمرارية", arCopy: "نمذج المدرج المالي بافتراضات وعملات واضحة والرافعة التالية التي يجب فحصها.", arDuration: "٥ دقائق · قابل للتصدير", arNext: "اختبر المدخلات" },
  { stage: "People", tag: "Build the role", title: "Hiring scorecard", copy: "Define the outcome, rubric, and evidence before the candidate conversation.", duration: "8 min · shareable", tone: "dark", href: "/tools/hiring-scorecard", next: "Draft the rubric", arTag: "ابنِ الدور", arTitle: "بطاقة تقييم التوظيف", arCopy: "حدد النتيجة والمعايير والأدلة قبل محادثة المرشح.", arDuration: "٨ دقائق · قابل للمشاركة", arNext: "صغ المعايير" },
  { stage: "People", tag: "Align the pair", title: "Co-founder quiz", copy: "Compare working preferences and turn the gaps into a useful conversation.", duration: "7 min · invite", tone: "soft", href: "/tools/cofounder-quiz", next: "Invite a co-founder", arTag: "وحد الشريكين", arTitle: "اختبار الشريك المؤسس", arCopy: "قارن تفضيلات العمل وحول الفجوات إلى محادثة مفيدة.", arDuration: "٧ دقائق · دعوة", arNext: "ادعُ شريكا مؤسسا" },
  { stage: "Readiness", tag: "Check the signal", title: "Series A readiness", copy: "Turn a complex readiness question into milestones with owners and evidence.", duration: "12 min · saveable", tone: "clay", href: "/tools/series-a-readiness", next: "Review evidence", arTag: "افحص الإشارة", arTitle: "الجاهزية للسلسلة A", arCopy: "حول سؤال الجاهزية المعقد إلى مراحل لها مسؤولون وأدلة.", arDuration: "١٢ دقيقة · قابل للحفظ", arNext: "راجع الأدلة" },
  { stage: "Baseline", tag: "Keep the rhythm", title: "Weekly scorecard", copy: "Review the week with the few numbers and notes that deserve your attention.", duration: "4 min · recurring", tone: "dark", href: "/tools/weekly-scorecard", next: "Set the rhythm", arTag: "حافظ على الإيقاع", arTitle: "بطاقة الأسبوع", arCopy: "راجع الأسبوع بالأرقام والملاحظات القليلة التي تستحق انتباهك.", arDuration: "٤ دقائق · متكرر", arNext: "اضبط الإيقاع" },
  { stage: "Strategy", tag: "Map the motion", title: "GTM channel map", copy: "Choose one audience, one channel, and the proof that earns the next test.", duration: "7 min · shareable", tone: "clay", href: "/tools/gtm-map", next: "Frame the channel test", arTag: "ارسم الحركة", arTitle: "خريطة قنوات الوصول", arCopy: "اختر جمهورا واحدا وقناة واحدة والدليل الذي يستحق الاختبار التالي.", arDuration: "٧ دقائق · قابل للمشاركة", arNext: "صغ اختبار القناة" },
  { stage: "Finance", tag: "Check the model", title: "Unit economics record", copy: "Make one retention, acquisition, or payback assumption visible before you scale it.", duration: "6 min · private", tone: "soft", href: "/tools/unit-economics", next: "Choose the metric", arTag: "افحص النموذج", arTitle: "سجل اقتصاديات الوحدة", arCopy: "اجعل افتراضا واحدا عن الاحتفاظ أو الاكتساب أو الاسترداد واضحا قبل توسيعه.", arDuration: "٦ دقائق · خاص", arNext: "اختر المقياس" },
  { stage: "Readiness", tag: "Build the room", title: "Fundraise evidence map", copy: "Turn an investor question into one evidence gap with a named owner.", duration: "9 min · saveable", tone: "dark", href: "/tools/fundraise-ready", next: "Name the evidence gap", arTag: "ابنِ الغرفة", arTitle: "خريطة دليل التمويل", arCopy: "حوّل سؤال المستثمر إلى فجوة دليل واحدة لها مالك محدد.", arDuration: "٩ دقائق · قابل للحفظ", arNext: "سمِ فجوة الدليل" },
  { stage: "Growth", tag: "Recover the cohort", title: "Retention recovery", copy: "Locate the churn signal, name the cohort, and choose one intervention to test.", duration: "8 min · actionable", tone: "soft", href: "/tools/retention-recovery", next: "Frame the intervention", arTag: "استعد المجموعة", arTitle: "استعادة الاحتفاظ", arCopy: "حدد إشارة التسرب وسمِ المجموعة واختر تدخلا واحدا لاختباره.", arDuration: "٨ دقائق · قابل للتنفيذ", arNext: "صغ التدخل" },
  { stage: "Strategy", tag: "Price the promise", title: "Pricing decision", copy: "Keep the buyer, value proof, and price hypothesis in one usable record.", duration: "6 min · evidence-led", tone: "dark", href: "/tools/pricing", next: "Test the hypothesis", arTag: "سعّر الوعد", arTitle: "قرار التسعير", arCopy: "أبقِ المشتري ودليل القيمة وفرضية السعر في سجل واحد قابل للاستخدام.", arDuration: "٦ دقائق · يقودها الدليل", arNext: "اختبر الفرضية" }
  ,{ stage: "Growth", tag: "Trace the signal", title: "SaaS health record", copy: "Turn one customer signal into a cohort-sized intervention you can learn from.", duration: "7 min · evidence-led", tone: "clay", href: "/tools/saas-health", next: "Choose the intervention", arTag: "تتبع الإشارة", arTitle: "سجل صحة SaaS", arCopy: "حول إشارة عميل واحدة إلى تدخل بحجم مجموعة يمكنك التعلم منه.", arDuration: "٧ دقائق · يقودها الدليل", arNext: "اختر التدخل" }
  ,{ stage: "Strategy", tag: "Map the alternative", title: "Market map", copy: "Make the customer’s current alternative and next market evidence visible.", duration: "8 min · shareable", tone: "soft", href: "/tools/market-map", next: "Collect the evidence", arTag: "ارسم البديل", arTitle: "خريطة السوق", arCopy: "اجعل البديل الحالي للعميل ودليل السوق التالي مرئيين.", arDuration: "٨ دقائق · قابل للمشاركة", arNext: "اجمع الدليل" }
  ,{ stage: "Strategy", tag: "Frame the value", title: "Positioning evidence record", copy: "Connect the current alternative, differentiated value, and one buyer-recognised proof.", duration: "8 min · evidence-led", tone: "dark", href: "/tools/positioning-evidence", next: "Test the frame", arTag: "صغ القيمة", arTitle: "سجل دليل التموضع", arCopy: "صل البديل الحالي بالقيمة المتمايزة وإثبات واحد يقر به المشتري.", arDuration: "٨ دقائق · يقودها الدليل", arNext: "اختبر الإطار" }
  ,{ stage: "Baseline", tag: "Listen for proof", title: "Customer evidence loop", copy: "Turn one assumption into customer language and a commitment signal worth acting on.", duration: "7 min · private", tone: "clay", href: "/tools/customer-evidence", next: "Plan the next interview", arTag: "أنصت للإثبات", arTitle: "حلقة دليل العميل", arCopy: "حول افتراضا واحدا إلى لغة عميل وإشارة التزام تستحق التصرف.", arDuration: "٧ دقائق · خاص", arNext: "خطط للمقابلة التالية" }
  ,{ stage: "Growth", tag: "Reach first value", title: "Activation evidence path", copy: "Name the first-value action, one setup friction, and a cohort-sized intervention to observe.", duration: "7 min · evidence-led", tone: "soft", href: "/tools/activation-evidence", next: "Run the activation test", arTag: "صل للقيمة الأولى", arTitle: "مسار دليل التفعيل", arCopy: "سمِ فعل القيمة الأولى واحتكاك إعداد واحدا وتدخلا بحجم مجموعة لملاحظته.", arDuration: "٧ دقائق · يقودها الدليل", arNext: "شغّل اختبار التفعيل" }
];

export default function Tools() {
  const { t, isRTL } = useLocale();
  const { message, showToast, clearToast } = useToast();
  const [stage, setStage] = useState<(typeof toolStages)[number]>("All decisions");
  const filteredTools = useMemo(() => stage === "All decisions" ? tools : tools.filter((tool) => tool.stage === stage), [stage]);
  const displayTools = filteredTools.map((tool) => ({ ...tool, tag: t(tool.tag, tool.arTag), title: t(tool.title, tool.arTitle), copy: t(tool.copy, tool.arCopy), duration: t(tool.duration, tool.arDuration), next: t(tool.next, tool.arNext) }));
  return <>
    <PageIntro label={t("Grow / Founder tools", "انمُ / أدوات المؤسس")} title={t("Turn uncertainty into a plan you can act on this week.", "حول عدم اليقين إلى خطة يمكنك تنفيذها هذا الأسبوع.")} copy={t("A small library of decision tools for founders who want to see the assumptions, make the call, and keep moving.", "مكتبة صغيرة من أدوات القرار للمؤسسين الذين يريدون رؤية الافتراضات واتخاذ القرار والاستمرار.")} note={<div className="tools-hero-workbench"><span className="mono">{t("WORKBENCH / PRIVATE BY DEFAULT", "طاولة عمل / خاص افتراضيا")}</span><div><span><b>01</b>{t("Input", "مدخل")}</span><span><b>02</b>{t("Test", "اختبر")}</span><span><b>03</b>{t("Act", "تحرك")}</span></div><p>{t("The tool shows what it asks, what it calculates, and the next test, not a mystery score.", "توضح الأداة ما تطلبه وما تحسبه والاختبار التالي، لا درجة غامضة.")}</p><button className="button button-primary button-small" onClick={() => showToast(t("Tool recommendation started with your founder brief.", "بدأت توصية أداة من موجز مؤسسك."))}>{t("Recommend a tool", "اقترح أداة")} {isRTL ? <ArrowLeft size={14} /> : <ArrowRight size={14} />}</button></div>} />
    <section className="section tool-pathway-section"><div className="container tool-pathway-layout"><div className="tool-pathway-brief"><SectionLabel>{t("The decision workbench", "طاولة عمل القرار")}</SectionLabel><h2>{t("Move from a question to a next step.", "انتقل من سؤال إلى خطوة تالية.")}</h2><p>{t("Every tool follows the same useful sequence: name the decision, make the assumptions visible, then choose what to do with the result.", "تتبع كل أداة التسلسل نفسه: سمِ القرار، اجعل الافتراضات مرئية، ثم اختر ما ستفعله بالنتيجة.")}</p><div className="tool-pathway-index"><span className="mono">{t("01 / FRAME", "٠١ / صِغ")}</span><strong>{t("What are you actually deciding?", "ما القرار الذي تتخذه فعلا؟")}</strong><span className="mono">{t("02 / TEST", "٠٢ / اختبر")}</span><strong>{t("Which assumption needs evidence?", "أي افتراض يحتاج إلى دليل؟")}</strong><span className="mono">{t("03 / ACT", "٠٣ / تحرك")}</span><strong>{t("Who or what moves next?", "من أو ماذا يتحرك بعد ذلك؟")}</strong></div></div><article className="tool-featured-card"><div className="tool-featured-top"><SignalTag>{t("Start here", "ابدأ هنا")}</SignalTag><span className="mono">{t("3 min · private", "٣ دقائق · خاص")}</span></div><h2>{t("Founder diagnostic", "تشخيص المؤسس")}</h2><p>{t("See the four dimensions shaping your next season of work, then turn the weakest signal into a practical brief.", "شاهد الأبعاد الأربعة التي تشكل موسم عملك التالي، ثم حول أضعف إشارة إلى موجز عملي.")}</p><div className="tool-featured-steps"><span><b>01</b> {t("Answer the baseline", "أجب عن خط الأساس")}</span><span><b>02</b> {t("See the pattern", "شاهد النمط")}</span><span><b>03</b> {t("Choose the next test", "اختر الاختبار التالي")}</span></div><div className="product-actions"><button className="button button-dark" onClick={() => showToast(t("Founder diagnostic started from your brief.", "بدأ تشخيص المؤسس من موجزك."))}>{t("Start diagnostic", "ابدأ التشخيص")} {isRTL ? <ArrowLeft size={15} /> : <ArrowRight size={15} />}</button><button className="button button-light" onClick={() => showToast(t("Tool recommendation started with your founder brief.", "بدأت توصية أداة من موجز مؤسسك."))}>{t("Recommend for me", "اقترح لي")}</button></div></article></div></section>
    <section className="section"><div className="container"><div className="section-header"><div><SectionLabel>{t("Choose by decision", "اختر حسب القرار")}</SectionLabel><h2>{t("Start with the thing you are trying to decide.", "ابدأ بالشيء الذي تحاول أن تقرره.")}</h2></div><p>{t("Every tool is short, transparent, and designed to end with a next action, not a mysterious score.", "كل أداة قصيرة وشفافة ومصممة لتنتهي بإجراء تال، لا بدرجة غامضة.")}</p></div><div className="tool-intent-controls" role="toolbar" aria-label={t("Filter tools by decision stage", "تصفية الأدوات حسب مرحلة القرار")}><SlidersHorizontal size={16} /><span className="mono">{t("Filter by stage", "تصفية حسب المرحلة")}</span>{toolStages.map((option) => <button type="button" key={option} className={stage === option ? "is-active" : ""} aria-pressed={stage === option} onClick={() => setStage(option)}>{t(option, stageArabic[option])}</button>)}</div><div className="tool-results-summary"><span className="mono">{displayTools.length} {t(displayTools.length === 1 ? "tool" : "tools", displayTools.length === 1 ? "أداة" : "أدوات")} {t("in view", "معروضة")}</span><span>{t("Short, transparent, and built to end in action.", "قصيرة وشفافة ومصممة لتنتهي بإجراء.")}</span></div><div className="tool-pathway-list">{displayTools.map((tool) => <ToolCard key={tool.title} {...tool} />)}</div></div></section>
    <section className="section section-clay"><div className="container"><div className="story-grid"><div><SectionLabel>{t("What a good tool does", "ما الذي تفعله الأداة الجيدة")}</SectionLabel><h2>{t("It makes the assumptions visible.", "تجعل الافتراضات مرئية.")}</h2><p>{t("Founder tools should earn trust through clarity. You should know how long the exercise takes, what it asks from you, how the output is calculated, and what to do after the result.", "يجب أن تكسب أدوات المؤسس الثقة بالوضوح. يجب أن تعرف مدة التمرين وما يطلبه منك وكيف تحسب النتيجة وماذا تفعل بعدها.")}</p><div className="story-list"><div><strong><ShieldCheck size={16} /> {t("Private inputs", "مدخلات خاصة")}</strong><span>{t("Trust", "ثقة")}</span></div><div><strong><Calculator size={16} /> {t("Clear assumptions", "افتراضات واضحة")}</strong><span>{t("Context", "سياق")}</span></div><div><strong><CircleGauge size={16} /> {t("Useful output", "نتيجة مفيدة")}</strong><span>{t("Action", "إجراء")}</span></div><div><strong><LineChart size={16} /> {t("Follow-through", "متابعة")}</strong><span>{t("Momentum", "زخم")}</span></div></div></div><div className="resource-card featured" style={{ minHeight: 360 }}><SignalTag>{t("Try the first one", "جرب الأولى")}</SignalTag><h3>{t("Build your founder brief.", "ابنِ موجز مؤسسك.")}</h3><p>{t("Tell us your stage, market, role, and what is difficult right now. Your answer shapes the people, events, resources, and tools you see first.", "أخبرنا بمرحلتك وسوقك ودورك وما الصعب الآن. إجابتك تشكل الأشخاص والفعاليات والموارد والأدوات التي تراها أولا.")}</p><button className="button button-primary" onClick={() => showToast(t("Founder brief flow opened.", "تم فتح مسار موجز المؤسس."))}>{t("Start my brief", "ابدأ موجزي")} {isRTL ? <ArrowLeft size={15} /> : <ArrowRight size={15} />}</button></div></div></div></section>
    <section className="section"><div className="container"><div className="section-header"><div><SectionLabel>{t("Tool safety", "سلامة الأدوات")}</SectionLabel><h2>{t("Helpful does not mean definitive.", "مفيد لا يعني حاسما.")}</h2></div><p>{t("Financial, hiring, and readiness outputs are prompts for better decisions, not a replacement for qualified professional advice.", "نتائج الأدوات المالية والتوظيف والجاهزية محفزات لقرارات أفضل، وليست بديلا عن المشورة المهنية المؤهلة.")}</p></div><div className="proof-strip"><div className="proof-cell accent"><CheckSquare2 size={18} /><strong style={{ marginTop: 10 }}>{t("Show the work", "أظهر العمل")}</strong><span>{t("Outputs should explain the reasoning behind them.", "يجب أن تشرح النتائج المنطق وراءها.")}</span></div><div className="proof-cell"><strong style={{ marginTop: 10 }}>{t("Name the limits", "اذكر الحدود")}</strong><span>{t("Tell people what the tool cannot evaluate.", "أخبر الناس بما لا تستطيع الأداة تقييمه.")}</span></div><div className="proof-cell"><strong style={{ marginTop: 10 }}>{t("Save the context", "احفظ السياق")}</strong><span>{t("Return to the inputs when the situation changes.", "عد إلى المدخلات عندما يتغير الموقف.")}</span></div><div className="proof-cell"><strong style={{ marginTop: 10 }}>{t("Ask for help", "اطلب المساعدة")}</strong><span>{t("Connect the result to a person or resource.", "اربط النتيجة بشخص أو مورد.")}</span></div></div></div></section>
    {message && <Toast message={message} onClose={clearToast} />}
  </>;
}
